from django.urls import re_path
from ..view.pharmacy_search import (
    ProductSearchView,
    ProductFormSearchView,
    ProductManufacturingCompanySearchView,
    ProductGroupSearchView,
    ProductSubgroupSearchView,
    ProductGenericSearchView,
    PurchaseSearchView,
    ProductCategorySearchView,
    PurchaseOrderPendingSearchView,
    PurchaseOrderCompletedSearchView,
    PurchaseOrderDiscardedSearchView,
    PurchaseRequisitionSearchView,
    EmployeeStorePointSearchView,
    # StockSearchView,
    StorePointSearchView,
    StockDisbursementSearchView,
    StockAdjustmentSearchView,
    UnitSearchView,
    DistributorOrderSearchView,
    ECommerceStockProductSearchView,
    ECommerceStockProductSearchSuggestView,
)
urlpatterns = [
    re_path(r'^product/$', ProductSearchView.as_view(),
        name="pharmacy.product-search"),
    re_path(r'^product/form/$', ProductFormSearchView.as_view(),
        name="pharmacy.product.form-search"),
    re_path(r'^product/manufacturer/$', ProductManufacturingCompanySearchView.as_view(),
        name="pharmacy.product.manufacturer-search"),
    re_path(r'^product/group/$', ProductGroupSearchView.as_view(),
        name="pharmacy-product-group-search"),
    re_path(r'^product/subgroup/$', ProductSubgroupSearchView.as_view(),
        name="pharmacy.product.subgroup-search"),
    re_path(r'^product/generic/$', ProductGenericSearchView.as_view(),
        name="pharmacy.product.generic-search"),
    re_path(r'^product/purchase/$', PurchaseSearchView.as_view(),
        name="pharmacy.product.purchase_search"),
    re_path(r'^product/category/$', ProductCategorySearchView.as_view(),
        name="pharmacy.product.category-search"),
    re_path(r'^product/purchase-order-pending/$', PurchaseOrderPendingSearchView.as_view(),
        name="pharmacy.product.purchase_order_pending_search"),
    re_path(r'^product/purchase-order-completed/$', PurchaseOrderCompletedSearchView.as_view(),
        name="pharmacy.product.purchase_order_completed_search"),
    re_path(r'^product/purchase-order-discarded/$', PurchaseOrderDiscardedSearchView.as_view(),
        name="pharmacy.product.purchase-order-discarded-search"),
    re_path(r'^product/purchase-requisition/$', PurchaseRequisitionSearchView.as_view(),
        name="pharmacy.product.purchase_requisition_search"),
    re_path(r'^storepoint/$', StorePointSearchView.as_view(),
        name="pharmacy.storepoint.search"),
    re_path(r'^employee-storepoint/(?P<employee_alias>[\w-]+)/$', EmployeeStorePointSearchView.as_view(
    ), name="pharmacy.employee-storepoint.search"),
    # re_path(r'^product/stock/$', StockSearchView.as_view(),
    #     name="pharmacy-stock-search"),
    re_path(r'^product/stock-disbursement/$',
        StockDisbursementSearchView.as_view(), name="pharmacy.stock-disbursement-search"),
    re_path(r'^product/stock-adjustment/$',
        StockAdjustmentSearchView.as_view(), name="pharmacy.stock-adjustment-search"),
    re_path(r'^unit/$', UnitSearchView.as_view(), name="pharmacy.unit-search"),
    re_path(r'^distributor/orders/$', DistributorOrderSearchView.as_view(),
        name="pharmacy.distributor.order-search"),
    re_path(
        r"^stock/products/e-com/$",
        ECommerceStockProductSearchView.as_view(),
        name="pharmacy.stock-search"
    ),
    re_path(
        r"^stock/products/suggestions/$",
        ECommerceStockProductSearchSuggestView.as_view(),
        name="pharmacy.stock-search.suggestions"
    ),
]
