# Generated by Django 2.2.9 on 2019-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_auto_20191128_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
