# Generated by Django 2.2.9 on 2020-01-03 09:51

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_publishedpromotionorder_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='promotion/images'),
        ),
    ]
