# Generated by Django 4.2.2 on 2023-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_alter_popupmessage_entry_by_alter_popupmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpopupmessage',
            name='expires_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedpopupmessage',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
