# Generated by Django 4.2.3 on 2023-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_publishedpopupmessage_expires_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
