# Generated by Django 4.2.2 on 2023-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_popupmessage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
