# Generated by Django 4.2.3 on 2023-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0013_popupmessage_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="popupmessage",
            name="first_published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="last_unpublished_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
