# Generated by Django 2.2.24 on 2021-12-17 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0204_organization_offer_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0151_purchase_invoice_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('product_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mrp', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('sale_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('avg_purchase_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('lowest_purchase_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('highest_purchase_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('margin', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('product_visibility_in_catelog', models.CharField(blank=True, max_length=24, null=True)),
                ('old_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('sold_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('purchase_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('short_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('return_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('new_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('prediction', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('new_order', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('suggested_purchase_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('purchase_order', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitem_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
            ],
            options={
                'verbose_name': 'Prediction Item',
                'verbose_name_plural': 'Prediction Items',
            },
        ),
        migrations.CreateModel(
            name='PurchasePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_purchaseprediction_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('prediction_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_predictions', to='core.ScriptFileStorage')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_purchaseprediction_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Purchase Prediction',
                'verbose_name_plural': 'Purchase Predictions',
                'unique_together': {('prediction_file',)},
            },
        ),
        migrations.CreateModel(
            name='PredictionItemSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitemsupplier_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('prediction_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_item_suggestions', to='procurement.PredictionItem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_item_suppliers', to='core.PersonOrganization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitemsupplier_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Prediction Item Supplier',
                'verbose_name_plural': 'Prediction Item Suppliers',
            },
        ),
        migrations.AddField(
            model_name='predictionitem',
            name='purchase_prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_items', to='procurement.PurchasePrediction'),
        ),
        migrations.AddField(
            model_name='predictionitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_prediction_items', to='pharmacy.Stock'),
        ),
        migrations.AddField(
            model_name='predictionitem',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitem_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
