# Generated by Django 2.2.24 on 2021-12-20 10:19

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procure_procureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='procureitem',
            name='prediction_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_items', to='procurement.PredictionItem'),
        ),
        migrations.AddField(
            model_name='procureitem',
            name='rate_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Ok'), (2, 'Higher Than Range'), (3, 'Lower Than Range')], db_index=True, default=1),
        ),
    ]
