# Generated by Django 2.2.24 on 2021-12-23 05:36

import common.fields
from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_auto_20211220_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionitem',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='predictionitemsupplier',
            name='priority',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Other')], db_index=True, default=4),
        ),
        migrations.AddField(
            model_name='procure',
            name='geo_location_data',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='procure',
            name='invoices',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='procure',
            name='operation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procure',
            name='operation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procure',
            name='remarks',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='procureitem',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='purchaseprediction',
            name='label',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='predictionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='procureitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
