# Generated by Django 2.2.24 on 2021-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20211223_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure',
            name='operation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procure',
            name='operation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
