# Generated by Django 2.2.25 on 2022-01-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0151_purchase_invoice_group'),
        ('procurement', '0005_auto_20211223_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure',
            name='requisition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_requisitions', to='pharmacy.Purchase'),
        ),
    ]
