# Generated by Django 2.2.25 on 2022-02-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_scriptfilestorage_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0008_procure_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionitem',
            name='marked_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Mark'), (2, 'Un Mark')], db_index=True, default=2),
        ),
        migrations.CreateModel(
            name='PredictionItemMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Mark'), (2, 'Un Mark')], db_index=True, default=1)),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_item_mark_employees', to='core.PersonOrganization')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitemmark_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('prediction_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_item_marks', to='procurement.PredictionItem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prediction_item_mark_suppliers', to='core.PersonOrganization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_predictionitemmark_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Prediction Item Mark',
                'verbose_name_plural': 'Prediction Item Marks',
            },
        ),
    ]
