# Generated by Django 2.2.25 on 2022-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_auto_20220209_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionitem',
            name='has_min_purchase_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictionitem',
            name='suggested_min_purchase_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
