# Generated by Django 2.2.25 on 2022-04-15 08:04

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_auto_20220408_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure',
            name='medium',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Physical'), (2, 'Digital Device'), (3, 'Other')], db_index=True, default=1),
        ),
    ]
