# Generated by Django 2.2.25 on 2022-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_procure_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionitem',
            name='worst_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
