# Generated by Django 2.2.25 on 2022-09-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_predictionitem_worst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionitem',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
