# Generated by Django 4.1.5 on 2023-03-22 10:27

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_procuregroup_procure_procure_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='procuregroup',
            name='current_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Draft'), (2, 'Order Placed'), (3, 'Picked'), (4, 'Delivered'), (5, 'Paid'), (6, 'Completed')], db_index=True, default=1, help_text='Define current status of procure'),
        ),
    ]
