# Generated by Django 4.1.5 on 2023-03-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0160_alter_productchangeslogs_compartment_and_more'),
        ('procurement', '0019_procuregroup_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procuregroup',
            name='requisition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_group_requisitions', to='pharmacy.purchase'),
        ),
    ]
