# Generated by Django 4.2.3 on 2023-08-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_procuregroup_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseprediction',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
