# Generated by Django 4.2.2 on 2023-09-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_personorganization_tagged_contractor_and_more'),
        ('procurement', '0021_purchaseprediction_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_contractors', to='core.personorganization'),
        ),
    ]
