# Generated by Django 4.2.4 on 2023-10-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_procurereturn_returnsettlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurereturn',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
