# Generated by Django 4.2.4 on 2023-11-02 08:33

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_remove_deliveryhub_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0171_productcategory_logo'),
        ('procurement', '0024_alter_procurereturn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure',
            name='credit_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procure',
            name='credit_cost_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procure',
            name='credit_cost_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procure',
            name='credit_payment_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procure',
            name='credit_payment_term_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procure',
            name='is_credit_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procure',
            name='open_credit_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procure',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.CreateModel(
            name='HistoricalProcurePayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20)),
                ('method_reference', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entry_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization', verbose_name='organization name')),
                ('procure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procure')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'historical procure payment',
                'verbose_name_plural': 'historical procure payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProcure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('sub_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Purchase'), (3, 'Order')], db_index=True, default=1)),
                ('operation_start', models.DateTimeField(blank=True, null=True)),
                ('operation_end', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
                ('invoices', models.CharField(blank=True, max_length=1024, null=True)),
                ('geo_location_data', common.fields.JSONTextField(blank=True, default='{}', null=True)),
                ('current_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Draft'), (2, 'Order Placed'), (3, 'Picked'), (4, 'Delivered'), (5, 'Paid'), (6, 'Completed')], db_index=True, default=1, help_text='Define current status of procure')),
                ('estimated_collection_time', models.DateTimeField(blank=True, null=True)),
                ('medium', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Physical'), (2, 'Digital Device'), (3, 'Other')], db_index=True, default=1)),
                ('shop_name', models.CharField(blank=True, help_text='The name will be user for print header', max_length=128, null=True, verbose_name='shop name')),
                ('credit_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('is_credit_purchase', models.BooleanField(default=False)),
                ('credit_payment_term', models.PositiveIntegerField(default=0)),
                ('credit_payment_term_date', models.DateField(blank=True, null=True)),
                ('credit_cost_percentage', models.PositiveIntegerField(default=0)),
                ('credit_cost_amount', models.PositiveIntegerField(default=0)),
                ('open_credit_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contractor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization')),
                ('copied_from', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procure')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization')),
                ('entry_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization', verbose_name='organization name')),
                ('procure_group', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procuregroup', verbose_name='procure group')),
                ('requisition', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharmacy.purchase')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'historical Procure',
                'verbose_name_plural': 'historical Procures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcurePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20)),
                ('method_reference', models.CharField(blank=True, max_length=255)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='organization name')),
                ('procure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procures', to='procurement.procure')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'index_together': {('organization', 'status')},
            },
        ),
    ]
