# Generated by Django 4.2.4 on 2023-11-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_remove_deliveryhub_areas'),
        ('pharmacy', '0171_productcategory_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0025_procure_credit_amount_procure_credit_cost_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProcureGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('num_of_boxes', models.IntegerField(default=0)),
                ('num_of_unique_boxes', models.IntegerField(default=0)),
                ('current_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Draft'), (2, 'Order Placed'), (3, 'Picked'), (4, 'Delivered'), (5, 'Paid'), (6, 'Completed')], db_index=True, default=1, help_text='Define current status of procure')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entry_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharmacy.purchase')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'historical Procure Group',
                'verbose_name_plural': 'historical Procure Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
