# Generated by Django 4.2.4 on 2023-11-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_historicalprocuregroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurepayment',
            name='procure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_payments', to='procurement.procure'),
        ),
    ]
