# Generated by Django 4.2.4 on 2023-11-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_remove_deliveryhub_areas'),
        ('procurement', '0027_alter_procurepayment_procure'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization'),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor_procure_groups', to='core.personorganization'),
        ),
    ]
