# Generated by Django 4.2.7 on 2023-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0028_historicalprocuregroup_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocure',
            name='credit_cost_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='historicalprocure',
            name='credit_cost_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='procure',
            name='credit_cost_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='procure',
            name='credit_cost_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
