# Generated by Django 4.2.4 on 2023-12-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0029_alter_historicalprocure_credit_cost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='cash_commission',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_cost_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_cost_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_payment_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_payment_term_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='is_credit_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='open_credit_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalprocurepayment',
            name='procure_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procuregroup'),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='cash_commission',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_cost_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_cost_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_payment_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_payment_term_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='is_credit_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='open_credit_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='procurepayment',
            name='procure_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procure_group_payments', to='procurement.procuregroup'),
        ),
    ]
