# Generated by Django 4.2.7 on 2024-01-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_historicalprocuregroup_cash_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocuregroup',
            name='credit_status',
            field=models.CharField(blank=True, choices=[('HOLD', 'Hold'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='procuregroup',
            name='credit_status',
            field=models.CharField(blank=True, choices=[('HOLD', 'Hold'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20),
        ),
    ]
