# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='bed',
            name='clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Bed'),
        ),
        migrations.AddField(
            model_name='bed',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Bed'),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='treatment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.TreatmentSession'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttreatmentsession',
            unique_together=set([('appointment_date', 'treatment_session', 'bed')]),
        ),
    ]
