# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170714_0825'),
        ('clinic', '0003_auto_20170623_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConsumedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('discount', models.FloatField(default='0.00')),
                ('remarks', models.CharField(max_length=256)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
                ('service_consumed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.ServiceConsumed')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='serviceconsumedgroup',
            unique_together=set([('service_consumed', 'code')]),
        ),
    ]
