# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointmenttreatmentsession_appointment_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsumed',
            name='discount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
