# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0006_auto_20170816_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumed_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
