# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 05:52
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20170816_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='confirmed',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Patient Created But Yet Unapproved'), (2, b'Dr. Created But Yet Unapproved'), (3, b'Approved By Both')], db_index=True, default=3),
        ),
    ]
