# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20170816_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Bed'),
        ),
    ]
