# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20170913_1337'),
        ('clinic', '0008_merge_20170913_1814'),
        ('clinic', '0007_auto_20170913_1746'),
    ]

    operations = [
    ]
