# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_serviceconsumed_payable'),
        ('clinic', '0011_auto_20170920_1536'),
    ]

    operations = [
    ]
