# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_merge_20170920_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsumed',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
