# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_merge_20170920_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmenttreatmentsession',
            unique_together=set([]),
        ),
    ]
