# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20170921_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmenttreatmentsession',
            unique_together=set([('appointment_date', 'treatment_session', 'bed')]),
        ),
    ]
