# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20170921_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttreatmentsession',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttreatmentsession',
            unique_together=set([('appointment_date', 'treatment_session', 'bed')]),
        ),
    ]
