# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20170921_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='patient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_patient_admission', to='clinic.PatientAdmission'),
        ),
    ]
