# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20170922_1552'),
        ('clinic', '0017_auto_20170921_1610'),
    ]

    operations = [
    ]
