# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20170921_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='cost_per_day',
            field=models.FloatField(default='0.00'),
        ),
    ]
