# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_merge_20170925_1905'),
        ('clinic', '0018_bed_cost_per_day'),
    ]

    operations = [
    ]
