# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_merge_20170925_2044'),
        ('clinic', '0019_merge_20170925_2025'),
    ]

    operations = [
    ]
