# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_merge_20170925_2044'),
        ('clinic', '0018_appointmenttreatmentsession_patient_admission'),
    ]

    operations = [
    ]
