# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_merge_20170926_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmissionbed',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
