# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20170927_1744'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0022_merge_20170927_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('entry_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('exit_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, b'Default'), (1, b'Entry'), (2, b'Exit')], db_index=True, default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_of', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.DutyShift')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
