# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 09:16
from __future__ import unicode_literals

import autoslug.fields
import common.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0024_auto_20170928_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubServiceReportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_global', enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=1)),
                ('clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.SubServiceReportField')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='labtest_for_report', to='clinic.Service')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubServiceReportFieldNormalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', enumerify.fields.SelectIntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Transsexual'), (3, b'Any')], db_index=True, default=3)),
                ('age_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('age_max', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('value_min', models.CharField(max_length=256)),
                ('value_max', models.CharField(max_length=256)),
                ('sub_service_report_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_field_of_labtest', to='clinic.SubServiceReportField')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_referer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='referer_honorarium',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='service_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='service/pic'),
        ),
        migrations.AddField(
            model_name='subservicereport',
            name='sub_service_report_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_value_of_labtest', to='clinic.SubServiceReportFieldNormalValue'),
        ),
        migrations.AlterUniqueTogether(
            name='subservicereportfield',
            unique_together=set([('sub_service', 'name')]),
        ),
    ]
