# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_auto_20171002_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservicereportfieldnormalvalue',
            options={'ordering': ('sub_service_report_field',)},
        ),
    ]
