# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20171002_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservicereport',
            name='sub_service_report_field',
        ),
        migrations.DeleteModel(
            name='SubServiceReport',
        ),
    ]
