# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_auto_20171003_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=256)),
                ('service_consumed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_of_service_consumed', to='clinic.ServiceConsumed')),
                ('sub_service_report_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_value_of_labtest', to='clinic.SubServiceReportField')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
