# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 13:16
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_subservicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_occupied',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Free'), (1, b'Engaged')], db_index=True, default=0),
        ),
    ]
