# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 10:06
from __future__ import unicode_literals

import clinic.mixins
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_subservicereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConsumedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', common.fields.TimestampImageField(upload_to='service/pic')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Highest comes first.')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-priority',),
            },
            bases=(models.Model, clinic.mixins.ImageThumbFieldMixin),
        ),
        migrations.RemoveField(
            model_name='serviceconsumed',
            name='service_image',
        ),
        migrations.AddField(
            model_name='serviceconsumedimage',
            name='service_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.ServiceConsumed'),
        ),
    ]
