# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_auto_20171006_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicereportfield',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='labtest_for_report', to='clinic.SubService'),
        ),
    ]
