# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_bed_is_occupied'),
        ('clinic', '0030_auto_20171009_1325'),
    ]

    operations = [
    ]
