# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_serviceconsumed_priority'),
        ('clinic', '0031_merge_20171010_1445'),
    ]

    operations = [
    ]
