# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_auto_20171010_1600'),
        ('clinic', '0033_auto_20171010_1631'),
    ]

    operations = [
    ]
