# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 13:36
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_merge_20171010_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=0),
        ),
    ]
