# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0036_auto_20171010_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
