# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0037_auto_20171011_1454'),
        ('clinic', '0037_auto_20171011_1531'),
    ]

    operations = [
    ]
