# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0040_auto_20171016_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentschedule',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentschedule',
            unique_together=set([]),
        ),
    ]
