# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0041_auto_20171018_1650'),
        ('clinic', '0041_auto_20171018_2014'),
    ]

    operations = [
    ]
