# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0042_merge_20171019_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttreatmentsession',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttreatmentsession',
            unique_together=set([]),
        ),
    ]
