# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 14:34
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0044_merge_20171030_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsection',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft')], db_index=True, default=0),
        ),
    ]
