# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0045_auto_20171030_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.BedSection'),
        ),
    ]
