# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0046_bed_bed_section'),
        ('clinic', '0046_appointmentschedulemissed'),
    ]

    operations = [
    ]
