# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0043_auto_20171031_1738'),
        ('clinic', '0046_bed_bed_section'),
        ('clinic', '0046_appointmentschedulemissed'),
    ]

    operations = [
    ]
