# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_merge_20171031_1800'),
        ('clinic', '0047_merge_20171101_1216'),
    ]

    operations = [
    ]
