# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0048_auto_20171101_1239'),
        ('clinic', '0048_merge_20171101_1225'),
    ]

    operations = [
    ]
