# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 08:29
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0049_merge_20171101_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Admission Bed'), (2, b'Operation Bed'), (3, b'Consultant Room')], db_index=True, default=1),
        ),
    ]
