# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0050_ward'),
        ('clinic', '0050_bed_bed_type'),
    ]

    operations = [
    ]
