# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0021_diagnosis_diagnosis_department'),
        ('clinic', '0051_merge_20171115_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_consultant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosis_department', to='prescription.DiagnosisDepartment'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='discharge_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
