# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0052_bed_ward'),
        ('clinic', '0052_auto_20171116_2032'),
    ]

    operations = [
    ]
