# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0054_auto_20171123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereport',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subservicereport',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_service_report_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
