# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:14
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0055_auto_20171201_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='service_consumed_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Pathology')], db_index=True, default=1),
        ),
    ]
