# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0057_admissionconsultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconsumedgroup',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_group', to='clinic.ServiceConsumedGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceconsumedgroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='serviceconsumedgroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='serviceconsumedgroup',
            name='service_consumed',
        ),
    ]
