# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0058_auto_20171222_1120'),
        ('clinic', '0058_auto_20171221_1154'),
    ]

    operations = [
    ]
