# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0059_merge_20171222_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='report_delivered',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='tentative_delivery_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
