# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0059_merge_20171222_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='sample_collection_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='sample_test_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
