# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 09:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0059_merge_20171222_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
