# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0060_auto_20180101_1515'),
        ('clinic', '0060_auto_20180101_1632'),
    ]

    operations = [
    ]
