# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0060_auto_20180101_1539'),
        ('clinic', '0061_merge_20180102_1130'),
    ]

    operations = [
    ]
