# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0061_merge_20180102_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconsumed',
            old_name='code',
            new_name='service_consumed_group',
        ),
    ]
