# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 10:20
from __future__ import unicode_literals

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0062_merge_20180102_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_appointment_schedules', to=settings.AUTH_USER_MODEL, validators=[common.validators.is_patient]),
        ),
    ]
