# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0062_merge_20180102_1550'),
        ('clinic', '0062_auto_20180103_1436'),
    ]

    operations = [
    ]
