# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0063_merge_20180103_1948'),
        ('clinic', '0063_auto_20180104_1620'),
    ]

    operations = [
    ]
