# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 11:14
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0066_auto_20180111_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='payment_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Cash'), (2, b'Advanced'), (3, b'Due'), (4, b'Partial'), (5, b'Free')], db_index=True, default=1),
        ),
    ]
