# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0067_serviceconsumedgroup_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_of_appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
