# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_organizationsetting_display_patient_is_positive'),
        ('clinic', '0068_auto_20180119_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='person_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_person_organization', to='core.PersonOrganization', verbose_name='service consumed of person of organization'),
        ),
    ]
