# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0069_serviceconsumed_person_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='send_sms_before',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
