# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0069_serviceconsumed_person_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='treatment_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.TreatmentSession'),
        ),
    ]
