# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 12:11
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0070_auto_20180123_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Confirmed'), (2, b'Request'), (3, b'Urgent'), (4, b'Rejected')], db_index=True, default=1),
        ),
    ]
