# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0070_auto_20180124_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='last_cron_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
