# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0071_appointmenttreatmentsession_type'),
        ('clinic', '0070_auto_20180124_1953'),
    ]

    operations = [
    ]
