# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0072_merge_20180125_1121'),
        ('clinic', '0071_appointmentschedule_last_cron_update'),
    ]

    operations = [
    ]
