# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0074_auto_20180308_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='referrer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
