# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0074_auto_20180308_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereportfieldnormalvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='value_max',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='value_min',
            field=models.CharField(max_length=2000),
        ),
    ]
