# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0075_patientadmission_referrer'),
        ('clinic', '0075_auto_20180313_1559'),
    ]

    operations = [
    ]
