# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 10:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0078_auto_20180321_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationfield',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
