# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0077_reportfieldcategory'),
        ('clinic', '0079_auto_20180321_1048'),
    ]

    operations = [
    ]
