# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0082_auto_20180322_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicereportfield',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_fields_of_labtest', to='clinic.SubService'),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='sub_service_report_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='normal_value_of_report_field', to='clinic.SubServiceReportField'),
        ),
    ]
