# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 05:46
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0082_auto_20180322_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='kind',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Consultation'), (2, b'Operation')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='kind',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Consultation'), (2, b'Operation')], db_index=True, default=2),
        ),
    ]
