# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0084_auto_20180322_1813'),
        ('clinic', '0083_auto_20180327_1521'),
    ]

    operations = [
    ]
