# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0085_merge_20180329_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereport',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
