# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_merge_20180404_0954'),
        ('clinic', '0085_merge_20180329_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='transaction_head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.TransactionHead'),
        ),
    ]
