# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0086_subservice_transaction_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='transaction_head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_services', to='account.TransactionHead'),
        ),
    ]
