# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0087_auto_20180406_0759'),
        ('clinic', '0086_subservicereport_unit'),
    ]

    operations = [
    ]
