# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0087_auto_20180406_0759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subservicereportfield',
            unique_together=set([]),
        ),
    ]
