# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0088_merge_20180408_0910'),
        ('clinic', '0088_auto_20180408_0657'),
    ]

    operations = [
    ]
