# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0089_merge_20180408_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicereport',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
