# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0091_diagnostictestsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesample_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subservice_of_sample', to='clinic.DiagnosticTestSample')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_of_subservice', to='clinic.SubService')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesample_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Sample of SubService',
                'verbose_name_plural': 'Samples of SubServices',
            },
        ),
        migrations.AlterIndexTogether(
            name='subservicesample',
            index_together=set([('sub_service', 'sample')]),
        ),
    ]
