# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0071_personorganization_is_dead'),
        ('clinic', '0092_auto_20180412_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceSampleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesamplecollection_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('service_consumed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples_of_service_consumed', to='clinic.ServiceConsumed')),
            ],
            options={
                'verbose_name': 'Sample Collection Of SubService',
                'verbose_name_plural': 'Samples Collection Of SubServices',
            },
        ),
        migrations.AddField(
            model_name='subservicesample',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservicesamplecollection',
            name='sub_service_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections_of_sample', to='clinic.SubServiceSample'),
        ),
        migrations.AddField(
            model_name='subservicesamplecollection',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesamplecollection_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
    ]
