# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0093_auto_20180416_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='samples',
            field=models.ManyToManyField(related_name='subservices_of_sample', through='clinic.SubServiceSample', to='clinic.DiagnosticTestSample'),
        ),
    ]
