# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0094_subservice_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='subservice_samples',
            field=models.ManyToManyField(related_name='service_consumed_of_subservice_sample', through='clinic.SubServiceSampleCollection', to='clinic.SubServiceSample'),
        ),
    ]
