# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0095_serviceconsumed_subservice_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereportfield',
            name='show_category',
            field=models.BooleanField(default=True),
        ),
    ]
