# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0096_subservicereportfield_show_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_service_lab_test', to='prescription.LabTest'),
        ),
    ]
