# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0097_auto_20180424_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconsumed',
            name='person_organization',
        ),
    ]
