# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20180427_1326'),
        ('clinic', '0097_auto_20180424_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='person_organization_referrer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referrer_person_organization', to='core.PersonOrganization', verbose_name='referrer person organization'),
        ),
    ]
