# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0098_remove_serviceconsumed_person_organization'),
        ('clinic', '0097_auto_20180424_1125'),
    ]

    operations = [
    ]
