# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0098_patientadmission_person_organization_referrer'),
        ('clinic', '0100_auto_20180511_1028'),
    ]

    operations = [
    ]
