# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0083_auto_20180517_0546'),
        ('clinic', '0101_merge_20180521_0924'),
    ]

    operations = [
    ]
