# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_patientbill'),
        ('clinic', '0101_merge_20180521_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconsumed',
            name='bill',
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_group_on_patient_bill', to='account.PatientBill'),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='payable',
            field=models.FloatField(default=0.0),
        ),
    ]
