# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0102_auto_20180525_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
