# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0102_merge_20180525_0917'),
        ('clinic', '0103_auto_20180525_0637'),
    ]

    operations = [
    ]
