# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0104_merge_20180529_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicesamplecollection',
            name='sample_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
