# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0105_subservicesamplecollection_sample_label'),
        ('clinic', '0105_patientadmission_bed_charge'),
    ]

    operations = [
    ]
