# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 10:12
from __future__ import unicode_literals

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0106_merge_20180622_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_appointment_schedules', to=settings.AUTH_USER_MODEL, validators=[common.validators.is_person_or_employee]),
        ),
    ]
