# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0107_auto_20180623_0730'),
        ('clinic', '0107_auto_20180623_1012'),
    ]

    operations = [
    ]
