# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0108_merge_20180623_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
