# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0109_auto_20180626_0627'),
        ('clinic', '0109_serviceconsumed_estimated_delivery_date'),
    ]

    operations = [
    ]
