# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20180703_1054'),
        ('clinic', '0111_serviceconsumedgroupsalestransation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='second_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_referer', to='core.PersonOrganization', verbose_name='reference from other person'),
        ),
    ]
