# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_personorganization_referrer_category'),
        ('clinic', '0112_serviceconsumed_second_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereport',
            name='person_organization_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_service_report_provider_person_organization', to='core.PersonOrganization', verbose_name='sub service report provider in person organization'),
        ),
    ]
