# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0114_organizationdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
