# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0115_serviceconsumed_department'),
        ('clinic', '0115_subservice_remarks'),
    ]

    operations = [
    ]
