# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0116_referrercategorydiscountgroup'),
        ('clinic', '0116_auto_20180813_1432'),
    ]

    operations = [
    ]
