# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0116_merge_20180808_0647'),
        ('clinic', '0117_merge_20180814_0641'),
    ]

    operations = [
    ]
