# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_discountgroup'),
        ('clinic', '0119_serviceconsumed_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='honorarium_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='honorarium_groups', to='core.DiscountGroup'),
        ),
    ]
