# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 11:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0120_subservice_honorarium_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsumed',
            name='referer_honorarium',
            field=models.FloatField(db_index=True, default=0.0, help_text='Honorarium in percentage (%)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
