# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 08:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0121_auto_20180818_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='paid',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='paid',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
