# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_merge_20180831_1542'),
        ('clinic', '0122_auto_20180827_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereportfieldnormalvalue',
            name='clone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.SubServiceReportFieldNormalValue'),
        ),
        migrations.AddField(
            model_name='subservicereportfieldnormalvalue',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='subservicereportfieldnormalvalue',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name'),
        ),
    ]
