# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0123_auto_20180910_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationfield',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='investigationfield',
            name='unit',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
