# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0124_auto_20180911_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicereportfield',
            name='category_priority',
            field=models.PositiveIntegerField(default=0, help_text='Highest comes first.'),
        ),
        migrations.AddField(
            model_name='subservicereportfield',
            name='field_priority',
            field=models.PositiveIntegerField(default=0, help_text='Highest comes first.'),
        ),
    ]
