# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0125_auto_20180913_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='value_max',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='value_min',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
