# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0126_auto_20180914_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionconsultant',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='appointmentschedulemissed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='appointmentserviceconsumed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='appointmenttreatmentsession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='bed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='bedsection',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='diagnostictestsample',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='dutyshift',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='employeesession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='investigationfield',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='patientadmissionbed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='referrercategorydiscountgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='reportfieldcategory',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='service',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='serviceconsumedgroupsalestransation',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='serviceconsumedimage',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservicereport',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservicereportfield',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservicereportfieldnormalvalue',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservicesample',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='subservicesamplecollection',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='ward',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
    ]
