# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_personorganization_diagnosis_with'),
        ('clinic', '0128_auto_20180920_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='report_verified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumeds_of_report_verifier', to='core.PersonOrganization', verbose_name='report verifier in person organization'),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='tested_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumeds_of_tester', to='core.PersonOrganization', verbose_name='tested by in person organization'),
        ),
    ]
