# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-27 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0135_employeebedsectionaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationfield',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='result',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
