# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0136_auto_20190328_1822'),
        ('clinic', '0136_auto_20190327_1432'),
    ]

    operations = [
    ]
