# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0137_merge_20190329_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumedgroup',
            name='sub_services',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
