# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0141_auto_20190725_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='service_consumed_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_with_appointment', to='clinic.ServiceConsumedGroup'),
        ),
    ]
