# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 08:55
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0142_auto_20190911_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionconsultant',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_admissionconsultant_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='admissionconsultant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='admissionconsultant',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='admissionconsultant',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='admissionconsultant',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_admissionconsultant_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='confirmed',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Patient Created But Yet Unapproved'), (2, 'Dr. Created But Yet Unapproved'), (3, 'Approved By Both')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='days',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentschedule_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='kind',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Consultation'), (2, 'Operation')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentschedule_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='appointmentschedulemissed',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentschedulemissed_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='appointmentschedulemissed',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='appointmentschedulemissed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='appointmentschedulemissed',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointmentschedulemissed',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentschedulemissed_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentserviceconsumed_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointmentserviceconsumed',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmentserviceconsumed_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='confirmed',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Patient Created But Yet Unapproved'), (2, 'Dr. Created But Yet Unapproved'), (3, 'Approved By Both')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmenttreatmentsession_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='kind',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Consultation'), (2, 'Operation')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Confirmed'), (2, 'Request'), (3, 'Urgent'), (4, 'Rejected')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='appointmenttreatmentsession',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_appointmenttreatmentsession_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Admission Bed'), (2, 'Operation Bed'), (3, 'Consultant Room')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='bed',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_bed_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bed',
            name='is_occupied',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Free'), (1, 'Engaged')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bed',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bed',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_bed_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='bedsection',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_bedsection_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='bedsection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='bedsection',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='bedsection',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bedsection',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_bedsection_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_diagnostictestsample_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnostictestsample',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_diagnostictestsample_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_dutyshift_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_dutyshift_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeeattendance_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Default'), (1, 'Entry'), (2, 'Exit')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeeattendance_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='employeebedsectionaccess',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeebedsectionaccess_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='employeebedsectionaccess',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='employeebedsectionaccess',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='employeebedsectionaccess',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeebedsectionaccess',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeebedsectionaccess_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='days',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeesession_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeesession',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_employeesession_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_investigationfield_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='investigationfield',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_investigationfield_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_organizationdepartment_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organizationdepartment',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_organizationdepartment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_patientadmission_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_patientadmission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='patientadmissionbed',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_patientadmissionbed_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='patientadmissionbed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='patientadmissionbed',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Admitted'), (2, 'Transfered'), (3, 'Checkedout')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='patientadmissionbed',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_patientadmissionbed_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='productofservice',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_productofservice_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='productofservice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='productofservice',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='productofservice',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productofservice',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_productofservice_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='referrercategorydiscountgroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_referrercategorydiscountgroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='referrercategorydiscountgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='referrercategorydiscountgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='referrercategorydiscountgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='referrercategorydiscountgroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_referrercategorydiscountgroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_reportfieldcategory_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportfieldcategory',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_reportfieldcategory_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='service',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_service_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Others')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Diagnostic'), (2, 'Others')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_service_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumed_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='priority',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Normal'), (1, 'Low'), (2, 'High')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='service_consumed_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Pathology')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceconsumed',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumed_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedgroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='payment_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Cash'), (2, 'Advanced'), (3, 'Due'), (4, 'Partial'), (5, 'Free')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedgroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroupsalestransation',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedgroupsalestransation_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroupsalestransation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroupsalestransation',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroupsalestransation',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceconsumedgroupsalestransation',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedgroupsalestransation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedimage',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedimage_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedimage',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='serviceconsumedimage',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceconsumedimage',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_serviceconsumedimage_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservice_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservice_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereport_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereport_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereportfield_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereportfield',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereportfield_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereportfieldnormalvalue_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='gender',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Transsexual'), (3, 'Any')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicereportfieldnormalvalue',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicereportfieldnormalvalue_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservicesample',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesample_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservicesample',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservicesample',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservicesample',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicesample',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesample_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='subservicesamplecollection',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesamplecollection_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='subservicesamplecollection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='subservicesamplecollection',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='subservicesamplecollection',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subservicesamplecollection',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_subservicesamplecollection_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_treatmentsession_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_treatmentsession_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_ward_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ward',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ward',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_ward_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
