# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0144_service_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='referrer_deduction',
            field=models.FloatField(default=0.0, help_text='deducted amount from referrer'),
        ),
    ]
