# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0146_serviceconsumed_special_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsumed',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
