# Generated by Django 2.2.7 on 2019-12-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0148_auto_20191127_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Ward'),
        ),
    ]
