# Generated by Django 2.2.9 on 2020-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0151_auto_20200225_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationfield',
            name='standard_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subservicereport',
            name='standard_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
