# Generated by Django 2.2.13 on 2020-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0153_organizationwisediscardedsubservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicereport',
            name='result',
            field=models.CharField(max_length=1024),
        ),
    ]
