# Generated by Django 4.2.7 on 2024-01-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0155_alter_admissionconsultant_entry_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrercategorydiscountgroup',
            name='discount_group',
        ),
        migrations.RemoveField(
            model_name='referrercategorydiscountgroup',
            name='referrer_category',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='honorarium_group',
        ),
    ]
