# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20170619_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
