# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20170714_0825'),
        ('pharmacy', '0005_stockiolog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('discount', models.FloatField(default=0.0)),
                ('transport', models.FloatField(default=0.0)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_transfer_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_from', to='pharmacy.StorePoint')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_to', to='pharmacy.StorePoint')),
            ],
            options={
                'verbose_name_plural': 'Stock Transfer',
            },
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_io_logs', to='pharmacy.StockTransfer'),
        ),
    ]
