# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_stocktransfer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='gave',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Cash'), (2, b'Credit')], db_index=True, default=2),
        ),
    ]
