# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_purchase_is_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_salesable',
            field=models.BooleanField(default=True),
        ),
    ]
