# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person_theme'),
        ('pharmacy', '0009_purchase_is_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_department', to='core.Department'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='requisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_total',
            field=models.FloatField(default=0.0),
        ),
    ]
