# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_merge_20170915_2009'),
        ('pharmacy', '0011_merge_20170915_2002'),
    ]

    operations = [
    ]
