# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0011_merge_20170915_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_io_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
