# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_stockiolog_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.Purchase'),
        ),
        migrations.AddField(
            model_name='sales',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.Sales'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.StockTransfer'),
        ),
    ]
