# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_stockiolog_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='demand',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productform',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productgeneric',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productmanufacturingcompany',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stockiolog',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='storepoint',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0),
        ),
    ]
