# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 10:59
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_stockiolog_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Proposed Transfer'), (1, b'Approved')], db_index=True, default=0),
        ),
    ]
