# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_auto_20170920_1536'),
        ('pharmacy', '0013_auto_20170920_1231'),
    ]

    operations = [
    ]
