# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_merge_20170920_1802'),
        ('pharmacy', '0013_stocktransfer_transfer_status'),
    ]

    operations = [
    ]
