# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_merge_20170920_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
