# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20170921_1610'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20170920_1536'),
        ('pharmacy', '0015_merge_20170920_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_product_disbrustment', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_adjustment_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_adjustment_patient', to=settings.AUTH_USER_MODEL)),
                ('patient_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_adjustment_patient_admission', to='clinic.PatientAdmission')),
                ('store_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_adjustment_store_point', to='pharmacy.StorePoint')),
            ],
            options={
                'verbose_name_plural': 'StockAdjustment',
            },
        ),
    ]
