# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_auto_20170922_1211'),
        ('pharmacy', '0016_auto_20170922_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_sales_transaction', to='account.Transaction'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='recived_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_transfer_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
