# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_auto_20170926_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='recived_by',
            new_name='received_by',
        ),
    ]
