# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_stockadjustment'),
        ('pharmacy', '0018_auto_20170926_1554'),
    ]

    operations = [
    ]
