# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_merge_20170926_2045'),
        ('pharmacy', '0016_auto_20170925_1835'),
    ]

    operations = [
    ]
