# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_merge_20170927_1203'),
        ('pharmacy', '0019_employeeaccountaccess'),
    ]

    operations = [
    ]
