# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_merge_20170927_1203'),
        ('pharmacy', '0020_merge_20170927_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='patient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_patient_admission', to='clinic.PatientAdmission'),
        ),
    ]
