# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20170926_2045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0021_merge_20170927_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStorepointAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_point_employee', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
                ('store_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_store_point', to='pharmacy.StorePoint')),
            ],
            options={
                'verbose_name_plural': 'EmployeeStorepointAccess',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeestorepointaccess',
            unique_together=set([('organization', 'employee', 'store_point')]),
        ),
    ]
