# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_merge_20170927_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_adjustment', to='pharmacy.StockAdjustment'),
        ),
    ]
