# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 06:39
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_auto_20171030_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccountaccess',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeestorepointaccess',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productform',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productgeneric',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productmanufacturingcompany',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stockiolog',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='storepoint',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Completed'), (4, b'Approved Draft'), (5, b'Absent')], db_index=True, default=0),
        ),
    ]
