# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_auto_20171101_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vouchar_no',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
