# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_sales_vouchar_no'),
        ('pharmacy', '0032_purchase_vouchar_no'),
    ]

    operations = [
    ]
