# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0033_merge_20171107_1256'),
        ('pharmacy', '0012_merge_20170915_2016'),
    ]

    operations = [
    ]
