# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0055_auto_20171201_1821'),
        ('pharmacy', '0035_auto_20171123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='service_consumed',
            field=models.ForeignKey(blank=True, help_text='Disbursement for pathology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumeds', to='clinic.ServiceConsumed'),
        ),
    ]
