# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 13:52
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0036_stockadjustment_service_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Requisition'), (2, b'Order'), (3, b'Purchase')], db_index=True, default=3),
        ),
    ]
