# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180109_1505'),
        ('pharmacy', '0037_purchase_purchase_type'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stock',
            index_together=set([('organization', 'status')]),
        ),
        migrations.AlterIndexTogether(
            name='stockiolog',
            index_together=set([('organization', 'status')]),
        ),
    ]
