# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 06:55
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0037_purchase_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_order_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Pending'), (3, b'Completed')], db_index=True, default=1),
        ),
    ]
