# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0038_purchase_purchase_order_type'),
        ('pharmacy', '0038_auto_20180109_1505'),
    ]

    operations = [
    ]
