# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0039_purchase_storepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='storepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_on_storepoint', to='pharmacy.StorePoint'),
        ),
    ]
