# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0039_merge_20180110_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_order_type',
            new_name='purchase_order_status',
        ),
    ]
