# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0040_auto_20180110_1229'),
        ('pharmacy', '0041_auto_20180111_1943'),
    ]

    operations = [
    ]
