# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 12:56
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0042_merge_20180115_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Pending'), (3, b'Completed'), (4, b'Discarded')], db_index=True, default=1),
        ),
    ]
