# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0043_auto_20180307_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='pharmacy.Purchase'),
        ),
    ]
