# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0044_auto_20180309_1030'),
        ('pharmacy', '0044_auto_20180313_1615'),
    ]

    operations = [
    ]
