# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0049_auto_20180411_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_unit', to='pharmacy.Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_unit', to='pharmacy.Unit'),
        ),
    ]
