# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 10:57
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pharmacy', '0051_auto_20180427_0718'), ('pharmacy', '0052_auto_20180427_1041')]

    dependencies = [
        ('pharmacy', '0050_auto_20180412_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='conversion_factor',
            field=models.FloatField(default=1.0, validators=[common.validators.positive_non_zero]),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='primary_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_io_primary_unit', to='pharmacy.Unit'),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='secondary_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_io_secondary_unit', to='pharmacy.Unit'),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='secondary_unit_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_factor',
            field=models.FloatField(default=1.0, validators=[common.validators.positive_non_zero]),
        ),
    ]
