# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0051_auto_20180427_0718_squashed_0052_auto_20180427_1041'),
        ('pharmacy', '0051_sales_bill'),
    ]

    operations = [
    ]
