# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0052_merge_20180514_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockiolog',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_io', to='pharmacy.Stock'),
        ),
    ]
