# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0052_merge_20180514_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='discount_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='discount_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='tax_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='vat_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='vat_total',
            field=models.FloatField(default=0.0),
        ),
    ]
