# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0052_merge_20180514_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
