# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:50
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0053_auto_20180514_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='disbursement_for',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Patient'), (3, b'Service Consumed')], db_index=True, default=1),
        ),
    ]
