# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0053_auto_20180514_0840'),
        ('pharmacy', '0053_sales_paid_amount'),
    ]

    operations = [
    ]
