# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0053_auto_20180529_0341'),
        ('pharmacy', '0054_auto_20180528_0841'),
    ]

    operations = [
    ]
