# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0054_stockadjustment_disbursement_for'),
        ('pharmacy', '0055_merge_20180529_0403'),
    ]

    operations = [
    ]
