# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0054_merge_20180525_0637'),
        ('pharmacy', '0056_merge_20180529_0616'),
    ]

    operations = [
    ]
