# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_merge_20180606_0342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0057_merge_20180529_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_purchaserequisition_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_of_requisition', to='pharmacy.Purchase')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisition_of_purchase', to='pharmacy.Purchase')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_purchaserequisition_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Requisition of Purchase',
                'verbose_name_plural': 'Requisitions of Purchases',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='requisitions',
            field=models.ManyToManyField(related_name='purchase_requisitions', through='pharmacy.PurchaseRequisition', to='pharmacy.Purchase'),
        ),
        migrations.AlterIndexTogether(
            name='purchaserequisition',
            index_together=set([('purchase', 'requisition')]),
        ),
    ]
