# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20180709_1118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0059_auto_20180626_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_purchasereturn_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_purchase', to='pharmacy.Purchase')),
            ],
            options={
                'verbose_name': 'Return Purchase',
                'verbose_name_plural': 'Return Purchases',
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='is_purchase_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_return', to='pharmacy.Sales'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_purchasereturn_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
    ]
