# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20180702_1304'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0059_auto_20180626_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_salesreturn_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_of_return_sales', to='pharmacy.Purchase')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_sales_for_purchase', to='pharmacy.Sales')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_salesreturn_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Return Sale',
                'verbose_name_plural': 'Return Sales',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='sales_return',
            field=models.ManyToManyField(related_name='sales_return_by_purchase', through='pharmacy.SalesReturn', to='pharmacy.Sales'),
        ),
    ]
