# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0060_auto_20180711_0802'),
        ('pharmacy', '0060_auto_20180705_1051'),
    ]

    operations = [
    ]
