# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0064_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccountaccess',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='employeestorepointaccess',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productform',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productgeneric',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productmanufacturingcompany',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='productsubgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='sales',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='storepoint',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
    ]
