# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0065_auto_20180919_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsubgroup',
            unique_together=set([]),
        ),
    ]
