# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0066_auto_20180920_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgeneric',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
