# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0067_auto_20180920_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='species',
            field=models.CharField(blank=True, help_text='Purpose of product', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='Strength of product', max_length=255, null=True),
        ),
    ]
