# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0068_auto_20180924_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='auto_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
