# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 06:03
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0069_stock_auto_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Manual'), (2, b'Auto'), (3, b'Other')], db_index=True, default=1),
        ),
    ]
