# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0069_stock_auto_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepoint',
            name='populate_global_product',
            field=models.BooleanField(default=False, help_text='Create stock for global products'),
        ),
    ]
