# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0070_storepoint_populate_global_product'),
        ('pharmacy', '0070_stockadjustment_adjustment_type'),
    ]

    operations = [
    ]
