# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0110_merge_20181001_1830'),
        ('pharmacy', '0072_auto_20180928_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_storeproductcategory_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_categoty_of_store', to='pharmacy.ProductCategory')),
                ('store_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_of_product_category', to='pharmacy.StorePoint')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_storeproductcategory_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Store Product Category',
                'verbose_name_plural': 'Stores Product Category',
            },
        ),
        migrations.AddField(
            model_name='storepoint',
            name='product_category',
            field=models.ManyToManyField(related_name='store_point_product_category', through='pharmacy.StoreProductCategory', to='pharmacy.ProductCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproductcategory',
            unique_together=set([('store_point', 'product_category')]),
        ),
    ]
