# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0073_auto_20181003_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
