# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_personorganization_diagnosis_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0075_productdisbursementcause'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIOLogDisbursementCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number')),
                ('number_of_usage', models.PositiveIntegerField(blank=True, default=None, help_text='Number of time used', null=True)),
                ('disbursement_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disbursement_causes_io_log', to='pharmacy.ProductDisbursementCause')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_stockiologdisbursementcause_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('stock_io_log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='io_log_disbursement_causes', to='pharmacy.StockIOLog')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_stockiologdisbursementcause_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Disbursement Cause of Stock IO Log',
                'verbose_name_plural': 'Disbursement Causes of Stock IO Logs',
            },
        ),
        migrations.AlterIndexTogether(
            name='stockiologdisbursementcause',
            index_together=set([('stock_io_log', 'disbursement_cause')]),
        ),
    ]
