# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0076_auto_20181011_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='minimum_stock',
            field=models.FloatField(default=0.0),
        ),
    ]
