# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0077_stock_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_form', to='pharmacy.ProductForm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_generic', to='pharmacy.ProductGeneric'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_manufacturing_company', to='pharmacy.ProductManufacturingCompany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_subgroup', to='pharmacy.ProductSubgroup'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subgroup_product_group', to='pharmacy.ProductGroup'),
        ),
    ]
