# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0078_auto_20181025_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rack',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
