# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0079_stock_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='order_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
