# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0080_auto_20181112_0618'),
        ('pharmacy', '0080_auto_20181109_0851'),
    ]

    operations = [
    ]
