# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0119_auto_20181114_1224'),
        ('pharmacy', '0082_auto_20181114_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_stocktransferrequisition_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
            ],
            options={
                'verbose_name': 'Requisition of StockTransfer',
                'verbose_name_plural': 'Requisitions of StockTransfer',
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requisitions',
            field=models.ManyToManyField(related_name='stock_transfer_requisitions', through='pharmacy.PurchaseRequisition', to='pharmacy.StockTransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferrequisition',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisition_of_stock_transfer', to='pharmacy.StockTransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferrequisition',
            name='stock_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_transfer_of_requisition', to='pharmacy.StockTransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferrequisition',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_stocktransferrequisition_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AlterIndexTogether(
            name='stocktransferrequisition',
            index_together=set([('stock_transfer', 'requisition')]),
        ),
    ]
