# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0084_merge_20181129_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='calculated_price',
            field=models.FloatField(default=0.0, help_text='Rate of individual product after calculating vat, tax, discount'),
        ),
    ]
