# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0085_stock_calculated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepoint',
            name='auto_adjustment',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable auto adjustment'),
        ),
    ]
