# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0086_storepoint_auto_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='round_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
