# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0088_sales_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='strength',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Code of product', max_length=255, null=True),
        ),
    ]
