# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0090_auto_20181213_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
