# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0091_purchase_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='discount_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales',
            name='vat_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales',
            name='vat_total',
            field=models.FloatField(default=0.0),
        ),
    ]
