# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0092_auto_20190110_0735'),
        ('pharmacy', '0092_auto_20190111_1209'),
    ]

    operations = [
    ]
