# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0094_auto_20190116_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='calculated_price',
            field=models.FloatField(default=0.0, help_text='Rate of individual product stockpoint-wise after calculating vat, tax, discount'),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='calculated_price_organization_wise',
            field=models.FloatField(default=0.0, help_text='Rate of individual product organization-wise after calculating vat, tax, discount'),
        ),
    ]
