# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0095_auto_20190117_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='latest_purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_purchase_unit', to='pharmacy.Unit', verbose_name='latest purchase unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_sale_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_sale_unit', to='pharmacy.Unit', verbose_name='latest sale unit'),
        ),
    ]
