# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0096_auto_20190130_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-local_count', '-organizationwise_count', '-global_count')},
        ),
    ]
