# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0097_auto_20190131_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-local_count', '-organizationwise_count', '-global_count', 'product__name')},
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='pharmacy_st_local_c_5e8b80_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productdisbursementcause',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productform',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productmanufacturingcompany',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storepoint',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['-local_count', '-organizationwise_count', '-global_count', 'product'], name='pharmacy_st_local_c_f8d099_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['status', 'product', 'store_point', 'stock', 'organization'], name='pharmacy_st_status_80ec57_idx'),
        ),
    ]
