# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0098_auto_20190201_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='round_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
