# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20190425_0544'),
        ('pharmacy', '0102_sales_sales_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='transactions',
            field=models.ManyToManyField(related_name='sales_tagged_transactions', through='account.SalesTransaction', to='account.Transaction'),
        ),
    ]
