# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0103_auto_20190502_1110'),
        ('pharmacy', '0103_sales_transactions'),
    ]

    operations = [
    ]
