# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 04:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0104_merge_20190514_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_category',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'GPA'), (3, b'GPB')], db_index=True, default=1),
        ),
    ]
