# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_organizationsetting_global_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0105_product_global_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('administration', models.TextField(blank=True, help_text='Way of Taking', null=True)),
                ('precaution', models.TextField(blank=True, help_text='Precautions & Warnings', null=True)),
                ('indication', models.TextField(blank=True, help_text='Indication of product', null=True)),
                ('contra_indication', models.TextField(blank=True, help_text='Contra-indication of product', null=True)),
                ('side_effect', models.TextField(blank=True, help_text='Side effects of product', null=True)),
                ('mode_of_action', models.TextField(blank=True, help_text='Mode of Action', null=True)),
                ('interaction', models.TextField(blank=True, help_text='Interaction / Connection', null=True)),
                ('adult_dose', models.TextField(blank=True, help_text='Adult Dose', null=True)),
                ('child_dose', models.TextField(blank=True, help_text='Child Dose', null=True)),
                ('renal_dose', models.TextField(blank=True, help_text='Renal Dose', null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_productadditionalinfo_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
            ],
            options={
                'verbose_name_plural': 'Products Additional Infos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full name(name + strength) of product', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='Strength(*mg) of product', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_additional_info', to='pharmacy.Product'),
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_productadditionalinfo_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
    ]
