# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0107_auto_20190527_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadditionalinfo',
            name='organization',
        ),
    ]
