# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-12 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0108_remove_productadditionalinfo_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyer_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
