# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0109_sales_buyer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_printable',
            field=models.BooleanField(default=True),
        ),
    ]
