# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0110_product_is_printable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='pharmacy_st_local_c_f8d099_idx',
        ),
        migrations.AddField(
            model_name='stock',
            name='product_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['-local_count', '-organizationwise_count', '-global_count', 'product_full_name', 'product_len'], name='pharmacy_st_local_c_4a7ac2_idx'),
        ),
    ]
