# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0112_auto_20190720_1217'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['organization', 'status', 'is_purchase_return'], name='pharmacy_sa_organiz_ded0f8_idx'),
        ),
    ]
