# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 08:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0114_auto_20190725_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='discount_margin',
            field=models.FloatField(default=0.0, help_text='discount margin as percentage(%)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
