# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 10:59
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0115_stock_discount_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiolog',
            name='data_entry_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Not Counted'), (2, b'Counted'), (3, b'Done')], db_index=True, default=3),
        ),
    ]
