# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 05:56
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0117_auto_20190826_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Retail Cash'), (2, b'Retail Credit'), (3, b'Whole Sale Cash'), (4, b'Whole Sale Credit')], db_index=True, default=2),
        ),
    ]
