# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-29 06:30
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0120_auto_20191127_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='inactive_from',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'From Active'), (2, 'From On Hold'), (3, 'From Edit')], db_index=True, default=1, help_text='Determine inactive sales which is from ACTIVE or ON_HOLD or EDIT'),
        ),
    ]
