# Generated by Django 2.2.7 on 2019-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0121_sales_inactive_from'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='pharmacy_st_status_e7a3a7_idx',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['status', 'is_salesable', 'store_point', 'stock', 'is_service', 'organization', 'product_full_name'], name='pharmacy_st_status_e7a3a7_idx'),
        ),
    ]
