# Generated by Django 2.2.8 on 2019-12-17 12:59

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0122_auto_20191205_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='vat_tax_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Product Wise')], db_index=True, default=1, help_text='What types of vat, tax, discount was selected during sales'),
        ),
    ]
