# Generated by Django 2.2.9 on 2020-01-13 08:33

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0123_sales_vat_tax_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published/Unpublished status of a product distributor'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_limit_per_day',
            field=models.FloatField(default=0.0),
        ),
    ]
