# Generated by Django 2.2.9 on 2020-01-13 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0124_auto_20200113_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.FloatField(default=0.0, help_text='Discount rate for order', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
