# Generated by Django 2.2.9 on 2020-01-16 10:55

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0125_product_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepoint',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Godown'), (1, 'Pharmacy'), (2, 'Vendor'), (3, 'Vendor Default')], db_index=True, default=1),
        ),
    ]
