# Generated by Django 2.2.9 on 2020-02-20 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0173_auto_20200207_1237'),
        ('pharmacy', '0127_product_alias_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Vendor / Distributor organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='distributor_order_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Cart'), (2, 'Order')], db_index=True, default=1, help_text='Define cart or order'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Requisition'), (2, 'Order'), (3, 'Purchase'), (4, 'Vendor Order')], db_index=True, default=3),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date time for status changed')),
                ('order_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled')], db_index=True, default=1, help_text='Define current status of order')),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_ordertracking_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('order', models.ForeignKey(help_text='The order for tracking', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_status', to='pharmacy.Purchase')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_ordertracking_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Trackings',
            },
        ),
        migrations.CreateModel(
            name='DistributorOrderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('sub_total', models.FloatField(default=0.0, help_text='SubTotal amount(excluding discount)')),
                ('discount', models.FloatField(default=0.0, help_text='Total Discount amount')),
                ('order_type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Cart'), (2, 'Order')], db_index=True, default=1, help_text='Define cart or order')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_distributorordergroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_distributorordergroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Distributor Order Group',
                'verbose_name_plural': 'Distributor Order Groups',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='distributor_order_group',
            field=models.ForeignKey(blank=True, help_text='Order group for distributor order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_groups', to='pharmacy.DistributorOrderGroup'),
        ),
    ]
