# Generated by Django 2.2.13 on 2020-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0129_auto_20200225_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorordergroup',
            name='round_discount',
            field=models.FloatField(default=0.0, help_text='Total Round Discount amount'),
        ),
    ]
