# Generated by Django 2.2.13 on 2020-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0130_distributorordergroup_round_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
