# Generated by Django 2.2.13 on 2020-07-19 09:28

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0131_stock_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='current_order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Partial Delivered'), (7, 'Completed'), (8, 'Rejected'), (9, 'Cancelled')], db_index=True, default=1, help_text='Define current status of order'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Partial Delivered'), (7, 'Completed'), (8, 'Rejected'), (9, 'Cancelled')], db_index=True, default=1, help_text='Define current status of order'),
        ),
    ]
