# Generated by Django 2.2.13 on 2020-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0132_auto_20200719_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='avg_purchase_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
