# Generated by Django 2.2.13 on 2020-08-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0134_sales_buyer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sales',
            field=models.ForeignKey(blank=True, help_text='Sales for an order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='pharmacy.Sales'),
        ),
    ]
