# Generated by Django 2.2.13 on 2020-08-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_personorganization_dropout_date'),
        ('pharmacy', '0136_auto_20200815_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributor_orders', to='core.PersonOrganization', verbose_name='responsible person organization for orders'),
        ),
    ]
