# Generated by Django 2.2.13 on 2020-11-11 06:36

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0137_purchase_responsible_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='system_platform',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Un Identified'), (2, 'Web App'), (3, 'Android App'), (4, 'IOS App')], db_index=True, default=2, help_text='Define system playform web/android-app/ios-app'),
        ),
    ]
