# Generated by Django 2.2.13 on 2021-01-07 10:08

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0140_auto_20201130_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='geo_location_data',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
    ]
