# Generated by Django 2.2.20 on 2021-07-06 09:01

from django.db import migrations, models
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0145_auto_20210624_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorordergroup',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_queueing_item',
            field=models.BooleanField(default=False, help_text='Next day flag for e-commerce'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_queueing_order',
            field=models.BooleanField(default=False, help_text='Next day flag for e-commerce'),
        ),
        migrations.AddField(
            model_name='stock',
            name='orderable_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled'), (9, 'Partial Delivered'), (10, 'Full Returned'), (11, 'In Queue')], db_index=True, default=1, help_text='Define current status of order'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='current_order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled'), (9, 'Partial Delivered'), (10, 'Full Returned'), (11, 'In Queue')], db_index=True, default=1, help_text='Define current status of order'),
        ),
    ]
