# Generated by Django 2.2.20 on 2021-07-26 09:21

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0147_purchase_tentative_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_mode',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Only Stock'), (2, 'Stock and Next Day'), (3, 'Open')], db_index=True, default=3),
        ),
    ]
