# Generated by Django 2.2.24 on 2021-08-03 10:19

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0148_product_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='calculated_profit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profit_data',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ecom_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='calculated_profit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stockiolog',
            name='profit_data',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
    ]
