# Generated by Django 2.2.24 on 2021-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0149_auto_20210803_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flash_item',
            field=models.BooleanField(default=False, help_text='Flash sale item flag'),
        ),
    ]
