# Generated by Django 2.2.24 on 2021-09-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_orderinvoicegroup'),
        ('pharmacy', '0150_product_is_flash_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_group',
            field=models.ForeignKey(blank=True, help_text='Order invoice group for distributor order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='ecommerce.OrderInvoiceGroup'),
        ),
    ]
