# Generated by Django 2.2.25 on 2022-01-21 12:51

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0152_auto_20220112_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Box'), (2, 'Strip'), (3, 'Box and Strip')], db_index=True, default=1),
        ),
    ]
