# Generated by Django 2.2.25 on 2022-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0153_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issue_number',
            field=models.IntegerField(default=0),
        ),
    ]
