# Generated by Django 2.2.25 on 2022-07-08 06:04

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0154_stock_issue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='failed_delivery_reason',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Unable to Reach'), (2, 'Unable to Find Address'), (3, 'Shop Closed'), (4, 'Other'), (5, 'Default')], db_index=True, default=5, help_text='Define reason for a failed delivery'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled'), (9, 'Partial Delivered'), (10, 'Full Returned'), (11, 'In Queue'), (12, 'Porter Delivered'), (13, 'Porter Full Return'), (14, 'Porter Partial Delivered'), (15, 'Porter Failed Delivered')], db_index=True, default=1, help_text='Define current status of order'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='current_order_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled'), (9, 'Partial Delivered'), (10, 'Full Returned'), (11, 'In Queue'), (12, 'Porter Delivered'), (13, 'Porter Full Return'), (14, 'Porter Partial Delivered'), (15, 'Porter Failed Delivered')], db_index=True, default=1, help_text='Define current status of order'),
        ),
    ]
