# Generated by Django 2.2.25 on 2022-10-27 09:07

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0211_employeemanager'),
        ('pharmacy', '0156_auto_20220715_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChangesLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('name', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('strength', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('generic', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('form', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('manufacturing_company', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('trading_price', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('purchase_price', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('order_limit_per_day', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('is_published', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('discount_rate', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('order_mode', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('is_flash_item', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('unit_type', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('compartment', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('is_queueing_item', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_productchangeslogs_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_logs', to='pharmacy.Product')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_productchangeslogs_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'index_together': {('organization', 'status')},
            },
        ),
    ]
