# Generated by Django 4.1.5 on 2023-03-21 06:36

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0158_alter_distributorordergroup_entry_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeslogs',
            name='is_salesable',
            field=common.fields.JSONTextField(blank=True, default='[]', null=True),
        ),
    ]
