# Generated by Django 4.1.5 on 2023-03-21 10:52

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0159_productchangeslogs_is_salesable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchangeslogs',
            name='compartment',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='discount_rate',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='form',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='generic',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='is_flash_item',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='is_published',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='is_queueing_item',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='is_salesable',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='manufacturing_company',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='name',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='order_limit_per_day',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='order_mode',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='purchase_price',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='strength',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='trading_price',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='productchangeslogs',
            name='unit_type',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
    ]
