# Generated by Django 4.1.6 on 2023-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0160_alter_productchangeslogs_compartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='remarks',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vouchar_no',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
