# Generated by Django 4.1.6 on 2023-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0162_stockreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='Strength(*mg) of product', max_length=64, null=True),
        ),
    ]
