# Generated by Django 4.2.2 on 2023-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0163_product_display_name_product_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_unpublish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
