# Generated by Django 4.2.3 on 2023-08-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0166_productmanufacturingcompany_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_add_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
