# Generated by Django 4.2.2 on 2023-08-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0167_stock_is_add_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='is_add_enabled',
            new_name='is_ad_enabled',
        ),
    ]
