# Generated by Django 4.2.3 on 2023-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0168_rename_is_add_enabled_stock_is_ad_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order_limit_per_day_mirpur",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="order_limit_per_day_uttara",
            field=models.FloatField(default=0.0),
        ),
    ]
