# Generated by Django 4.2.3 on 2023-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0169_product_order_limit_per_day_mirpur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productchangeslogs",
            name="order_limit_per_day_mirpur",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="productchangeslogs",
            name="order_limit_per_day_uttara",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="compartment",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="discount_rate",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="form",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="generic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="is_flash_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="is_published",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="is_queueing_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="is_salesable",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="manufacturing_company",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="name",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="order_limit_per_day",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="order_mode",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="purchase_price",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="strength",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="trading_price",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="productchangeslogs",
            name="unit_type",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
