# Generated by Django 4.2.4 on 2023-11-13 11:50

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0172_product_minimum_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='logo',
            field=common.fields.TimestampVersatileImageField(blank=True, null=True, upload_to='logo/images'),
        ),
    ]
