# Generated by Django 4.2.4 on 2023-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0173_productgroup_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
