# Generated by Django 5.0 on 2023-12-29 09:26

import enumerify.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0174_purchase_is_delayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_mode',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Only Stock'), (2, 'Stock and Next Day'), (3, 'Open'), (4, 'Stock and Open')], db_index=True, default=3),
        ),
    ]
