# Generated by Django 4.2.7 on 2024-01-26 10:37

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_invoicepdfgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0229_remove_district_division_remove_district_entry_by_and_more'),
        ('pharmacy', '0176_remove_stockiolog_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_invoice_group', to='ecommerce.orderinvoicegroup')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_product_reported_by_user', to='core.personorganization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('rechecked_date', models.DateTimeField(auto_now_add=True)),
                ('total_missing_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_extra_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('recheck_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_invoice_group', to='ecommerce.orderinvoicegroup')),
                ('rechecked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_product_request_by_user', to='core.personorganization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecheckProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('manufacturer_company_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_image', common.fields.TimestampVersatileImageField(blank=True, null=True, upload_to='product/images')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('EXTRA', 'Extra'), ('MISSING', 'Missing')], default='EXTRA', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_product_approved_by_user', to='core.personorganization')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('recheck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_io', to='pharmacy.recheck')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_product_stock', to='pharmacy.stock')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DamageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('manufacturer_company_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_image', common.fields.TimestampVersatileImageField(blank=True, null=True, upload_to='product/images')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discounted_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('type', models.CharField(choices=[('RETURN_DAMAGE', 'Return Damage'), ('DISTRIBUTION_DAMAGE', 'Distribution Damage')], default='RETURN_DAMAGE', max_length=30)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_io', to='pharmacy.damage')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_product_invoice_group', to='ecommerce.orderinvoicegroup')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_product_stock', to='pharmacy.stock')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
