# Generated by Django 4.2.7 on 2024-01-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_invoicepdfgroup_area'),
        ('pharmacy', '0177_damage_recheck_recheckproduct_damageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheck',
            name='top_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_product_top_sheets', to='ecommerce.invoicegroupdeliverysheet'),
        ),
        migrations.AddField(
            model_name='recheckproduct',
            name='invoice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_item_invoice_group', to='ecommerce.orderinvoicegroup'),
        ),
        migrations.AddField(
            model_name='recheckproduct',
            name='order_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recheck',
            name='invoice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recheck_invoice_group', to='ecommerce.orderinvoicegroup'),
        ),
    ]
