# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Accounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.TransactionHead'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paying_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receive_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Accounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiongroup',
            unique_together=set([('transaction', 'code')]),
        ),
    ]
