# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170714_0825'),
        ('account', '0003_auto_20170622_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
