# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170714_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
    ]
