# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 07:17
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170714_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transaction'},
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='group',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Patient'), (2, b'Employee'), (3, b'Supplier')], db_index=True, default=0),
        ),
    ]
