# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20170802_1310'),
        ('account', '0006_auto_20170718_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_of', to='pharmacy.Sales'),
        ),
    ]
