# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170802_1310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiongroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transactiongroup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='transactiongroup',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='TransactionGroup',
        ),
    ]
