# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 07:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170802_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhead',
            name='group',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Patient'), (2, b'Employee'), (3, b'Supplier'), (4, b'Other')], db_index=True, default=0),
        ),
    ]
