# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:01
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170913_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhead',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Capital'), (2, b'Recurring')], db_index=True, default=1),
        ),
    ]
