# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170913_1804'),
        ('account', '0009_auto_20170913_1337'),
    ]

    operations = [
    ]
