# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_20170915_1927'),
        ('account', '0010_transactionhead_type'),
    ]

    operations = [
    ]
