# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20170927_1744'),
        ('account', '0013_auto_20170922_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together=set([('organization', 'name')]),
        ),
    ]
