# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 14:23
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170928_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhead',
            name='group',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Patient'), (2, b'Employee'), (3, b'Supplier'), (4, b'Stack Holder'), (5, b'Referrer'), (6, b'Other')], db_index=True, default=0),
        ),
    ]
