# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_auto_20171013_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='ac_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'a/c number'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'bank name'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='branch',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'branch of bank'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_accounts_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_accounts_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'bank or mobile banking provider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'branch if any'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transaction_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipt_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'cheque, bank draft or reference no'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transaction_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transactionhead_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transactionhead_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Accounts', verbose_name=b'a/c'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='admission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_transaction', to='clinic.PatientAdmission', verbose_name=b'for admission of'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'unique code for group transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Cash'), (2, b'Cheque'), (3, b'Mobile Banking')], db_index=True, default=0, verbose_name=b'method of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paying_by', to=settings.AUTH_USER_MODEL, verbose_name=b'transaction by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receive_by', to=settings.AUTH_USER_MODEL, verbose_name=b'employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_of', to='pharmacy.Sales', verbose_name=b'for sales of'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_consumed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_transaction', to='clinic.ServiceConsumed', verbose_name=b'for service consumption of'),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='group',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Patient'), (2, b'Employee'), (3, b'Supplier'), (4, b'Stack Holder'), (5, b'Referrer'), (6, b'Other'), (7, b'Service Provider')], db_index=True, default=0, verbose_name=b'group of transaction head'),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Capital'), (2, b'Recurring')], db_index=True, default=1, verbose_name=b'type of head'),
        ),
    ]
