# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20171020_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vouchar_no',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
