# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20171030_1915'),
        ('account', '0022_transaction_vouchar_no'),
    ]

    operations = [
    ]
