# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 14:42
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20171101_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(validators=[common.validators.validate_non_zero_amount]),
        ),
    ]
