# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0049_merge_20171101_1523'),
        ('account', '0025_auto_20171110_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='appointment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_transaction', to='clinic.AppointmentTreatmentSession', verbose_name=b'for appointment of'),
        ),
    ]
