# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20171114_1601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together=set([]),
        ),
    ]
