# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0057_admissionconsultant'),
        ('account', '0030_auto_20171123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_consumed_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_group_transaction', to='clinic.ServiceConsumedGroup', verbose_name=b'for group service consumption of'),
        ),
    ]
