# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0031_transaction_service_consumed_group'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transaction',
            index_together=set([('date', 'accounts', 'head', 'method'), ('date',), ('date', 'paid_by'), ('date', 'received_by')]),
        ),
    ]
