# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180109_1505'),
        ('account', '0033_auto_20180109_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='person_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid_by_person_organization', to='core.PersonOrganization', verbose_name=b'transaction by person of organization'),
        ),
    ]
