# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 05:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20180126_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='payabletoperson',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Addition'), (2, b'Deduction'), (3, b'Other')], db_index=True, default=1, verbose_name=b'payable type'),
        ),
    ]
