# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organizationsetting_trace_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0042_merge_20180115_1908'),
        ('account', '0038_auto_20180212_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transactionpurchase_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_purchase', to='pharmacy.Purchase')),
            ],
            options={
                'verbose_name': 'Purchase To Transaction',
                'verbose_name_plural': 'Purchase To Transactions',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Sale'), (2, b'Admission'), (3, b'Appointment'), (4, b'Service Consumed'), (5, b'Purchase'), (6, b'Others')], db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='transactionpurchase',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_transaction', to='account.Transaction'),
        ),
        migrations.AddField(
            model_name='transactionpurchase',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_transactionpurchase_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchases',
            field=models.ManyToManyField(through='account.TransactionPurchase', to='pharmacy.Purchase'),
        ),
    ]
