# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_transaction_account_cheque'),
        ('account', '0039_auto_20180214_1157'),
    ]

    operations = [
    ]
