# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_merge_20180215_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchases',
            field=models.ManyToManyField(related_name='purchases_transaction', through='account.TransactionPurchase', to='pharmacy.Purchase'),
        ),
    ]
