# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20180306_1853'),
        ('account', '0041_auto_20180220_1959'),
    ]

    operations = [
    ]
