# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180323_1311'),
        ('account', '0042_merge_20180307_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='person_organization_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_by_person_organization', to='core.PersonOrganization', verbose_name=b'employee person organization'),
        ),
    ]
