# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_merge_20180307_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcheque',
            name='reference_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, verbose_name=b'reference name'),
        ),
    ]
