# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_transaction_person_organization_received'),
        ('account', '0043_transactionpurchase_amount'),
    ]

    operations = [
    ]
