# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_merge_20180327_1124'),
        ('account', '0043_auto_20180319_0551'),
    ]

    operations = [
    ]
