# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_person_pagination_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0047_transactionhead_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Due'), (2, b'Paid'), (3, b'Partial')], db_index=True, default=1, verbose_name=b'payment status')),
                ('partial_payment_amount', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_patientbill_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('person_organization_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_bill_person_organization', to='core.PersonOrganization', verbose_name=b'patient in person organization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_patientbill_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Patient Bill',
                'verbose_name_plural': 'Patient Bills',
            },
        ),
    ]
