# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_patientbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_department', to='account.AccountsDepartment', verbose_name=b'department of transaction'),
        ),
    ]
