# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_transaction_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_payable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='current_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='previous_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='previous_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
