# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20180711_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, default=None, help_text=b'Serial Number', null=True),
        ),
    ]
