# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_transactiongroup_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsdepartment',
            name='clone',
        ),
        migrations.RemoveField(
            model_name='accountsdepartment',
            name='entry_by',
        ),
        migrations.RemoveField(
            model_name='accountsdepartment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='accountsdepartment',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='clinic.OrganizationDepartment', verbose_name=b'department of transaction'),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head', to='clinic.OrganizationDepartment', verbose_name=b'department of transaction head'),
        ),
        migrations.DeleteModel(
            name='AccountsDepartment',
        ),
    ]
