# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20180803_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcheque',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='payabletoperson',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='transactionpurchase',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
    ]
