# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20180919_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_in_note',
            field=models.FloatField(default=0.0),
        ),
    ]
