# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20190103_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcheque',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payabletoperson',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transactionpurchase',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
