# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 07:01
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_auto_20190116_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Sale'), (2, b'Admission'), (3, b'Appointment'), (4, b'Service Consumed'), (5, b'Others'), (6, b'Purchase')], db_index=True, default=5),
        ),
    ]
