# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_auto_20190123_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
