# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20190219_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_of_bill', to='account.PatientBill'),
        ),
    ]
