# Generated by Django 2.2.8 on 2019-12-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_auto_20191127_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationwisediscardedtransactionhead',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_wise_discarded_parent_head', to='account.TransactionHead'),
        ),
    ]
