# Generated by Django 2.2.19 on 2021-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_notification', '0002_auto_20201021_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='app_version',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
