# Generated by Django 4.2.2 on 2023-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_notification', '0005_notification_pushtoken_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
