# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COUNTRIES_BY_TLD = (
    ('ac', "Ascension Island"),
    ('ad', "Andorra"),
    ('ae', "United Arab Emirates"),
    ('af', "Afghanistan	 "),
    ('ag', "Antigua and Barbuda"),
    ('ai', "Anguilla"),
    ('al', "Albania"),
    ('am', "Armenia"),
    ('an', "Netherlands Antilles"),
    ('ao', "Angola"),
    ('aq', "Antarctica"),
    ('ar', "Argentina"),
    ('as', "American Samoa"),
    ('at', "Austria"),
    ('au', "Australia"),
    ('aw', "Aruba"),
    ('az', "Azerbaijan"),
    ('ba', "Bosnia and Herzegovina"),
    ('bb', "Barbados"),
    ('bd', "Bangladesh"),
    ('be', "Belgium"),
    ('bf', "Burkina Faso"),
    ('bg', "Bulgaria"),
    ('bh', "Bahrain"),
    ('bi', "Burundi"),
    ('bj', "Benin"),
    ('bm', "Bermuda"),
    ('bn', "Brunei Darussalam"),
    ('bo', "Bolivia"),
    ('br', "Brazil"),
    ('bs', "Bahamas"),
    ('bt', "Bhutan"),
    ('bv', "Bouvet Island"),
    ('bw', "Botswana"),
    ('by', "Belarus"),
    ('bz', "Belize"),
    ('ca', "Canada"),
    ('cc', "Cocos (Keeling) Islands"),
    ('cd', "Democratic Republic of the Congo (Formerly Zaire)"),
    ('cf', "Central African Republic"),
    ('cg', "Republic of the Congo"),
    ('ch', "Switzerland"),
    ('ci', "Côte d'Ivoire"),
    ('ck', "Cook Islands"),
    ('cl', "Chile"),
    ('cm', "Cameroon"),
    ('cn', "People's Republic of China"),
    ('co', "Colombia"),
    ('cr', "Costa Rica"),
    ('cu', "Cuba"),
    ('cv', "Cape Verde"),
    ('cx', "Christmas Island"),
    ('cy', "Cyprus"),
    ('cz', "Czech Republic"),
    ('de', "Germany (Deutschland)"),
    ('dj', "Djibouti"),
    ('dk', "Denmark"),
    ('dm', "Dominica"),
    ('do', "Dominican Republic"),
    ('dz', "Algeria"),
    ('ec', "Ecuador"),
    ('ee', "Estonia"),
    ('eg', "Egypt"),
    ('er', "Eritrea"),
    ('es', "Spain (España)"),
    ('et', "Ethiopia"),
    ('eu', "European Union"),
    ('fi', "Finland"),
    ('fj', "Fiji"),
    ('fk', "Falkland Islands"),
    ('fm', "Federated States of Micronesia"),
    ('fo', "Faroe Islands"),
    ('fr', "France"),
    ('ga', "Gabon"),
    ('gb', "United Kingdom"),
    ('gd', "Grenada"),
    ('ge', "Georgia"),
    ('gf', "French Guiana"),
    ('gg', "Guernsey"),
    ('gh', "Ghana"),
    ('gi', "Gibraltar"),
    ('gl', "Greenland"),
    ('gm', "The Gambia"),
    ('gn', "Guinea"),
    ('gp', "Guadeloupe"),
    ('gq', "Equatorial Guinea"),
    ('gr', "Greece"),
    ('gs', "South Georgia and the South Sandwich Islands"),
    ('gt', "Guatemala"),
    ('gu', "Guam"),
    ('gw', "Guinea-Bissau"),
    ('gy', "Guyana"),
    ('hk', "Hong Kong"),
    ('hm', "Heard Island and McDonald Islands"),
    ('hn', "Honduras"),
    ('hr', "Croatia (Hrvatska)"),
    ('ht', "Haiti"),
    ('hu', "Hungary"),
    ('id', "Indonesia"),
    ('ie', "Ireland"),
    ('il', "Israel"),
    ('im', "Isle of Man"),
    ('in', "India"),
    ('io', "British Indian Ocean Territory"),
    ('iq', "Iraq"),
    ('ir', "Iran"),
    ('is', "Iceland"),
    ('it', "Italy"),
    ('je', "Jersey"),
    ('jm', "Jamaica"),
    ('jo', "Jordan"),
    ('jp', "Japan"),
    ('ke', "Kenya"),
    ('kg', "Kyrgyzstan"),
    ('kh', "Cambodia (Khmer)"),
    ('ki', "Kiribati"),
    ('km', "Comoros"),
    ('kn', "Saint Kitts and Nevis"),
    ('kr', "South Korea"),
    ('kw', "Kuwait"),
    ('ky', "Cayman Islands"),
    ('kz', "Kazakhstan"),
    ('la', "Laos"),
    ('lb', "Lebanon"),
    ('lc', "Saint Lucia"),
    ('li', "Liechtenstein"),
    ('lk', "Sri Lanka"),
    ('lr', "Liberia"),
    ('ls', "Lesotho"),
    ('lt', "Lithuania"),
    ('lu', "Luxembourg"),
    ('lv', "Latvia"),
    ('ly', "Libya"),
    ('ma', "Morocco"),
    ('mc', "Monaco"),
    ('md', "Moldova"),
    ('me', "Montenegro"),
    ('mg', "Madagascar"),
    ('mh', "Marshall Islands"),
    ('mk', "Republic of Macedonia"),
    ('ml', "Mali"),
    ('mm', "Myanmar"),
    ('mn', "Mongolia"),
    ('mo', "Macau"),
    ('mp', "Northern Mariana Islands"),
    ('mq', "Martinique"),
    ('mr', "Mauritania"),
    ('ms', "Montserrat"),
    ('mt', "Malta"),
    ('mu', "Mauritius"),
    ('mv', "Maldives"),
    ('mW', "Malawi"),
    ('mx', "Mexico"),
    ('my', "Malaysia"),
    ('mz', "Mozambique"),
    ('na', "Namibia"),
    ('nc', "New Caledonia"),
    ('ne', "Niger"),
    ('nF', "Norfolk Island"),
    ('ng', "Nigeria"),
    ('ni', "Nicaragua"),
    ('nl', "Netherlands"),
    ('no', "Norway"),
    ('np', "Nepal"),
    ('nr', "Nauru"),
    ('nu', "Niue"),
    ('nz', "New Zealand"),
    ('om', "Oman"),
    ('pa', "Panama"),
    ('pe', "Peru"),
    ('pF', "French Polynesia With Clipperton Island"),
    ('pg', "Papua New Guinea"),
    ('ph', "Philippines"),
    ('pk', "Pakistan"),
    ('pl', "Poland"),
    ('pm', "Saint-Pierre and Miquelon"),
    ('pn', "Pitcairn Islands"),
    ('pr', "Puerto Rico"),
    ('ps', "Palestinian territories	ie, West Bank and Gaza Strip"),
    ('pt', "Portugal"),
    ('pw', "Palau"),
    ('py', "Paraguay"),
    ('qa', "Qatar"),
    ('re', "Réunion"),
    ('ro', "Romania"),
    ('rs', "Serbia"),
    ('ru', "Russia"),
    ('rw', "Rwanda"),
    ('sa', "Saudi Arabia"),
    ('sb', "Solomon Islands"),
    ('sc', "Seychelles"),
    ('sd', "Sudan"),
    ('se', "Sweden"),
    ('sg', "Singapore"),
    ('sh', "Saint Helena"),
    ('si', "Slovenia"),
    ('sj', "Svalbard and Jan Mayen Islands"),
    ('sk', "Slovakia"),
    ('sl', "Sierra Leone"),
    ('sm', "San Marino"),
    ('sn', "Senegal"),
    ('so', "Somalia"),
    ('sr', "Suriname"),
    ('st', "São Tomé and Príncipe"),
    ('su', "Soviet Union"),
    ('sv', "El Salvador"),
    ('sy', "Syria"),
    ('sz', "Swaziland"),
    ('tc', "Turks and Caicos Islands"),
    ('td', "Chad"),
    ('tf', "French Southern and Antarctic Lands"),
    ('tg', "Togo"),
    ('th', "Thailand"),
    ('tj', "Tajikistan"),
    ('tk', "Tokelau"),
    ('tl', "Timor-Leste"),
    ('tm', "Turkmenistan"),
    ('tn', "Tunisia"),
    ('to', "Tonga"),
    ('tp', "East Timor"),
    ('tr', "Turkey"),
    ('tt', "Trinidad and Tobago"),
    ('tv', "Tuvalu"),
    ('tw', "Taiwan"),
    ('tz', "Tanzania"),
    ('ua', "Ukraine"),
    ('ug', "Uganda"),
    ('uk', "United Kingdom"),
    ('um', "United States Minor Outlying Islands"),
    ('us', "United States of America"),
    ('uy', "Uruguay"),
    ('uz', "Uzbekistan"),
    ('va', "Vatican City State"),
    ('vc', "Saint Vincent and the Grenadines"),
    ('ve', "Venezuela"),
    ('vg', "British Virgin Islands"),
    ('vi', "US Virgin Islands"),
    ('vn', "Vietnam"),
    ('vu', "Vanuatu"),
    ('wf', "Wallis and Futuna"),
    ('ws', "Samoa (Formerly Western Samoa)"),
    ('ye', "Yemen"),
    ('yt', "Mayotte"),
    ('yu', "Yugoslavia"),
    ('za', "South Africa"),
    ('zm', "Zambia"),
    ('zw', "Zimbabwe"),
)

COUNTRIES = sorted(COUNTRIES_BY_TLD, key=lambda item: item[1])


CURRENCIES_BY_CODE = [
    ('EUR', 'EUR'),
    ('SEK', 'SEK'),
    ('USD', 'USD')
]

DATEFORMAT = [
    ('dd/MM/yy', '03/08/06'),
    ('dd/MM/yyyy', '03/08/2006'),
    ('d/M/yy', '3/8/06'),
    ('d/M/yyyy', '3/8/2006'),
    ('ddMMyy', '030806'),
    ('ddMMyyyy', '03082006'),
    ('ddMMMyy', '03Aug06'),
    ('ddMMMyyyy', '03Aug2006'),
    ('dd-MMM-yy', '03-Aug-06'),
    ('dd-MMM-yyyy', '03-Aug-2006'),
    ('dMMMyy', '3Aug06'),
    ('dMMMyyyy', '3Aug2006'),
    ('d-MMM-yy', '3-Aug-06'),
    ('d-MMM-yyyy', '3-Aug-2006'),
    ('d-MMMM-yy', '3-August-06'),
    ('d-MMMM-yyyy', '3-August-2006'),
    ('yyMMdd', '060803'),
    ('yyyyMMdd', '20060803'),
    ('yy/MM/dd', '06/08/03'),
    ('yyyy/MM/dd', '2006/08/03'),
    ('MMddyyyy', '08032006'),
    ('MM/dd/yy', '08/03/06'),
    ('MM/dd/yyyy', '08/03/2006'),
    ('MMM-dd-yy', 'Aug-03-06'),
    ('MMM-dd-yyyy', 'Aug-03-2006'),
    ('yyyy-MM-dd', '2006-08-03'),
    ('dd-MM-yyyy', '03-08-2006')
]

CURRENCIES = sorted(CURRENCIES_BY_CODE, key=lambda item: item[1])


LANGUAGE_CODES = [
    ('bn', 'Bangla'),
    ('en', 'English')
]

LANGUAGES = sorted(LANGUAGE_CODES, key=lambda item: item[1])
