# Generated by Django 2.2.20 on 2021-06-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0198_auto_20210531_1332'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0143_auto_20210413_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortReturnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('order_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('short_return_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_order_items', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_order_unique_items', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_short_return_items', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_short_return_unique_items', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Short'), (2, 'Return')], db_index=True, default=1)),
                ('round_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_shortreturnlog_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_return_orders', to='pharmacy.Purchase')),
                ('order_by_organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_return_organization_order_by', to='core.Organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_return_received_by', to='core.PersonOrganization', verbose_name='Person Organization entry a short or return')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_shortreturnlog_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'index_together': {('organization', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ShortReturnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Short'), (2, 'Return')], db_index=True, default=1)),
                ('product_name', models.CharField(max_length=512)),
                ('order_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('batch', models.CharField(max_length=128)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discount_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('vat_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('vat_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('unit_name', models.CharField(max_length=56)),
                ('round_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_shortreturnitem_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('short_return_log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_return_items', to='ecommerce.ShortReturnLog')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_short_return', to='pharmacy.Stock')),
                ('stock_io', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_io_short_return', to='pharmacy.StockIOLog')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_shortreturnitem_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'index_together': {('organization', 'status')},
            },
        ),
    ]
