# Generated by Django 2.2.24 on 2021-09-30 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0203_organizationsetting_overwrite_order_mode_by_product'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('round_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_discount_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_cost', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_cost_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('current_order_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Ready to Deliver'), (4, 'On the Way'), (5, 'Delivered'), (6, 'Completed'), (7, 'Rejected'), (8, 'Cancelled'), (9, 'Partial Delivered'), (10, 'Full Returned'), (11, 'In Queue')], db_index=True, default=1, help_text='Define current status of order')),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_orderinvoicegroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('order_by_organization', models.ForeignKey(help_text='Organization order by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_groups', to='core.Organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_groups', to='core.PersonOrganization', verbose_name='responsible person organization for order group')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_orderinvoicegroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Order Invoice Group',
                'verbose_name_plural': 'Order Invoice Groups',
            },
        ),
    ]
