# Generated by Django 2.2.25 on 2022-03-09 14:54

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0205_scriptfilestorage_date'),
        ('ecommerce', '0003_shortreturnlog_invoice_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGroupDeliverySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('query_params', common.fields.JSONTextField(blank=True, default='{}', null=True)),
                ('filter_data', common.fields.JSONTextField(blank=True, default='{}', null=True)),
                ('total_data', common.fields.JSONTextField(blank=True, default='{}', null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_invoicegroupdeliverysheet_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User generate the report', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_by_invoice_group_delivery_sheets', to='core.PersonOrganization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('responsible_employee', models.ForeignKey(blank=True, help_text='Filter responsible employee(delivery guy)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_group_delivery_sheets', to='core.PersonOrganization')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_invoicegroupdeliverysheet_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Invoice Group Delivery Sheet',
                'verbose_name_plural': 'Invoice Group Delivery Sheets',
            },
        ),
        migrations.CreateModel(
            name='DeliverySheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('total_unique_item_order', models.IntegerField(default=0)),
                ('total_unique_item_short', models.IntegerField(default=0)),
                ('total_unique_item_return', models.IntegerField(default=0)),
                ('total_item_order', models.IntegerField(default=0)),
                ('total_item_short', models.IntegerField(default=0)),
                ('total_item_return', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_deliverysheetitem_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group_delivery_sheet', models.ForeignKey(help_text='Invoice group delivery sheet instance', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sheet_items', to='ecommerce.InvoiceGroupDeliverySheet')),
                ('order_by_organization', models.ForeignKey(help_text='Organization of a delivery sheet item', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_group_delivery_sheet_items', to='core.Organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_deliverysheetitem_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Delivery Sheet Item',
                'verbose_name_plural': 'Delivery Sheet Items',
            },
        ),
        migrations.CreateModel(
            name='DeliverySheetInvoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('sub_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('round_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_cost', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_short', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_return', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('delivery_sheet_item', models.ForeignKey(help_text='Delivery sheet item', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sheet_invoice_groups', to='ecommerce.DeliverySheetItem')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_deliverysheetinvoicegroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group', models.ForeignKey(help_text='Invoice group instance', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sheet_invoice_groups', to='ecommerce.OrderInvoiceGroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommerce_deliverysheetinvoicegroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Delivery Sheet Invoice Group',
                'verbose_name_plural': 'Delivery Sheet Invoice Groups',
            },
        ),
    ]
