# Generated by Django 2.2.25 on 2022-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_deliverysheetinvoicegroup_deliverysheetitem_invoicegroupdeliverysheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegroupdeliverysheet',
            name='order_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='invoicegroupdeliverysheet',
            name='return_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='invoicegroupdeliverysheet',
            name='short_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='total_return',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='total_short',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
