# Generated by Django 2.2.28 on 2022-06-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20220325_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.OrderInvoiceGroup'),
        ),
    ]
