# Generated by Django 2.2.25 on 2022-10-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20220914_1520'),
        ('ecommerce', '0007_auto_20220708_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegroupdeliverysheet',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator of the delivery guy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinator_invoice_group_delivery_sheets', to='core.PersonOrganization'),
        ),
        migrations.AddField(
            model_name='shortreturnlog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_return_approved_by', to='core.PersonOrganization', verbose_name='Person Organization approve a short or return'),
        ),
    ]
