# Generated by Django 2.2.25 on 2022-10-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_employeemanager'),
        ('ecommerce', '0008_auto_20221004_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='secondary_responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_invoice_groups', to='core.PersonOrganization', verbose_name='secondary responsible person organization for order group'),
        ),
    ]
