# Generated by Django 4.1.5 on 2023-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='sell_quantity_per_week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
    ]
