# Generated by Django 4.1.6 on 2023-06-08 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0216_organization_geo_location'),
        ('ecommerce', '0015_alter_orderinvoicegroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysheetitem',
            name='invoice_group_delivery_sub_sheet',
            field=models.ForeignKey(blank=True, default=None, help_text='Invoice group delivery sheet instance for sub top sheet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_top_sheet_delivery_sheet_items', to='ecommerce.invoicegroupdeliverysheet'),
        ),
        migrations.AddField(
            model_name='invoicegroupdeliverysheet',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('SUB_TOP_SHEET', 'Sub Top Sheet'), ('DISTRIBUTOR_TOP_SHEET', 'Distributor Top Sheet')], default='DEFAULT', max_length=50),
        ),
        migrations.CreateModel(
            name='TopSheetSubTopSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='organization name')),
                ('sub_top_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_top_sheets', to='ecommerce.invoicegroupdeliverysheet')),
                ('top_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_sheets', to='ecommerce.invoicegroupdeliverysheet')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'TopSheetSubTopSheet',
                'verbose_name_plural': 'TopSheetSubTopSheets',
            },
        ),
    ]
