# Generated by Django 4.2.7 on 2024-01-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_deliverysheetitem_invoice_group_delivery_sub_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='additional_dynamic_discount_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Additional discount amount customer get due to dynamic discount', max_digits=19),
        ),
        migrations.AddField(
            model_name='orderinvoicegroup',
            name='additional_dynamic_discount_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Additional discount percentage customer get due to dynamic discount', max_digits=19),
        ),
    ]
