# Generated by Django 4.2.7 on 2024-01-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_remove_district_division_remove_district_entry_by_and_more'),
        ('ecommerce', '0019_invoicepdfgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepdfgroup',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_pdf_groups', to='core.area'),
        ),
    ]
