# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
