# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20170704_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
