# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20170705_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
