# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20170706_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_curable',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
