# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 07:20
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_auto_20170714_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_allergy',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft')], db_index=True, default=1),
        ),
    ]
