# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0010_medicineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
