# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0015_auto_20171011_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondiagnosis',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosis_list', to='prescription.Prescription'),
        ),
    ]
