# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0016_auto_20171012_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosis_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosis_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='dietschedule',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dietschedule_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='dietschedule',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dietschedule_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='dose',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dose_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='dose',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dose_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_labtest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_labtest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_medicineschedule_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_medicineschedule_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_physicaltest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_physicaltest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescription_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescription_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescriptiondiagnosis',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiondiagnosis_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescriptiondiagnosis',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiondiagnosis_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescriptionlabtest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionlabtest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescriptionlabtest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionlabtest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescriptionphysicaltest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionphysicaltest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescriptionphysicaltest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionphysicaltest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescriptionsymptom',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionsymptom_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescriptionsymptom',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionsymptom_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='prescriptiontreatment',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiontreatment_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='prescriptiontreatment',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiontreatment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_symptom_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_symptom_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
    ]
