# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0020_diagnosisdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_of_diagnosis', to='prescription.DiagnosisDepartment'),
        ),
    ]
