# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0053_merge_20171117_1909'),
        ('prescription', '0022_auto_20171115_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_admission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_for_inhouse_patient', to='clinic.PatientAdmission'),
        ),
    ]
