# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180109_1505'),
        ('prescription', '0024_auto_20171123_1545'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='prescription',
            index_together=set([('organization', 'status')]),
        ),
    ]
