# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0025_auto_20180109_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='current_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Latest'), (2, b'Crossed Away'), (3, b'Other')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_origin', to='prescription.Prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='immediate_parent', to='prescription.Prescription'),
        ),
    ]
