# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0027_auto_20180327_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='person_organization',
            new_name='person_organization_patient',
        ),
    ]
