# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0029_auto_20180626_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='interval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
