# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0030_auto_20180917_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='diagnosisdepartment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='dietschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='dose',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescriptiondiagnosis',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescriptionlabtest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescriptionphysicaltest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescriptionsymptom',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='prescriptiontreatment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text=b'OrganizationWise Serial Number'),
        ),
    ]
