# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0031_auto_20180919_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='is_allergy',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='is_curable',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='dependency_disease',
            field=models.BooleanField(default=False, help_text='Trace a diagnosis have dependency or not'),
        ),
    ]
