# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 08:17
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0033_auto_20181016_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Previous'), (2, b'Current')], db_index=True, default=1, help_text='Diagnosis Type'),
        ),
    ]
