# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0036_auto_20181114_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisdepartment',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dietschedule',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dose',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondiagnosis',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionlabtest',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionphysicaltest',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionsymptom',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontreatment',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
