# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 14:36
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0041_auto_20190702_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='reminder',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dose',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='reminder',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionextrainfo',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionsymptom',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order'), (7, b'Suspend'), (8, b'On Hold'), (9, b'Hardwired'), (10, b'Loss'), (11, b'Freeze')], db_index=True, default=0),
        ),
    ]
