# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 07:37
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0042_auto_20190725_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosis_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosis_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosisdepartment_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diagnosisdepartment',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_diagnosisdepartment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dietschedule_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='reminder',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dietschedule_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dose_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dose',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='dose',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dose',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_dose_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_labtest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_labtest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_medicineschedule_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='reminder',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_medicineschedule_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_physicaltest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_physicaltest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='current_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Latest'), (2, 'Crossed Away'), (3, 'Other')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescription_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Normal'), (1, 'Medical Record')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescription_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionadditionalinfo_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionadditionalinfo',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionadditionalinfo_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiondiagnosis_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Previous'), (2, 'Current')], db_index=True, default=1, help_text='Diagnosis Type'),
        ),
        migrations.AlterField(
            model_name='prescriptiondiagnosis',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiondiagnosis_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptionextrainfo',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionextrainfo_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptionextrainfo',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptionextrainfo',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionextrainfo',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionextrainfo_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionlabtest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='state',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Pre Operation'), (1, 'Post Operation'), (2, 'During Operation')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionlabtest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionphysicaltest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='state',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Pre Operation'), (1, 'Post Operation'), (2, 'During Operation')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionphysicaltest',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionphysicaltest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptionsymptom',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionsymptom_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptionsymptom',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptionsymptom',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionsymptom',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptionsymptom_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiontreatment_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptiontreatment',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_prescriptiontreatment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_symptom_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_symptom_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
