# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20191202_0940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0044_auto_20191127_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationWiseDiscardedPhysicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('entry_type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Edit'), (2, 'Merge'), (3, 'Other')], db_index=True, default=1)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_organizationwisediscardedphysicaltest_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_wise_discarded_parent_physical_test', to='prescription.PhysicalTest')),
                ('physical_test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_wise_discarded_physical_test', to='prescription.PhysicalTest')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_organizationwisediscardedphysicaltest_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': "Organization's Discarded Physical Tests",
            },
        ),
        migrations.AlterIndexTogether(
            name='organizationwisediscardedphysicaltest',
            index_together=set([('organization', 'physical_test')]),
        ),
    ]
