# Generated by Django 2.2.8 on 2019-12-06 06:17

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0045_auto_20191204_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionadditionalinfo',
            name='usage',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'One Time'), (2, 'Two Times'), (3, 'Any')], db_index=True, default=1),
        ),
    ]
