# Generated by Django 2.2.9 on 2020-02-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0150_subservice_global_category'),
        ('prescription', '0046_prescriptionadditionalinfo_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_service_consumed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription_service_consumeds', to='clinic.ServiceConsumed'),
        ),
    ]
