# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:25
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170704_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relatives_relation',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Father'), (1, b'Mother'), (2, b'Spouse'), (3, b'Brother'), (4, b'Sister'), (5, b'Uncle'), (6, b'Aunt'), (7, b'Brother in Law'), (8, b'Sister in Law'), (9, b'Father in Law'), (10, b'Friends'), (11, b'Helping Hand'), (99, b'Other')], db_index=True, default=0),
        ),
    ]
