# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user should be treated as active. Unselect this instead of\n         deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[(b'bn', b'Bangla'), (b'en', b'English')], default=b'en', max_length=2),
        ),
    ]
