# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170922_1211'),
        ('core', '0010_auto_20170920_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='cash_sale_transaction_head',
            field=models.ForeignKey(blank=True, help_text='select transaction head for cash sale', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.TransactionHead'),
        ),
    ]
