# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationsetting_cash_sale_transaction_head'),
        ('core', '0011_grouppermission_personorganization_personorganizationgrouppermission'),
    ]

    operations = [
    ]
