# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20170926_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='personorganization',
            unique_together=set([('person', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='personorganizationgrouppermission',
            unique_together=set([('person_organization', 'permission')]),
        ),
    ]
