# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170922_1901'),
        ('core', '0013_auto_20170927_1623'),
    ]

    operations = [
    ]
