# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 09:16
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20170927_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Transsexual'), (3, b'Any')], db_index=True, default=0),
        ),
    ]
