# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 14:23
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171002_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Other')], db_index=True, default=0),
        ),
    ]
