# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 13:44
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171010_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=0),
        ),
    ]
