# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20171010_1944'),
        ('core', '0019_auto_20171010_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='transfer_from_transaction_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_from', to='account.TransactionHead'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='transfer_to_transaction_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_to', to='account.TransactionHead'),
        ),
    ]
