# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171010_1641'),
        ('core', '0020_auto_20171011_2029'),
        ('core', '0020_auto_20171011_1454'),
    ]

    operations = [
    ]
