# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20171012_1903'),
        ('core', '0021_merge_20171012_1430'),
    ]

    operations = [
    ]
