# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0041_auto_20171018_2014'),
        ('core', '0023_organizationsetting_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_service',
            field=models.ForeignKey(blank=True, help_text='select service for sub-service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Service'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='date_format',
            field=models.CharField(choices=[(b'dd/MM/yy', b'03/08/06'), (b'dd/MM/yyyy', b'03/08/2006'), (b'd/M/yy', b'3/8/06'), (b'd/M/yyyy', b'3/8/2006'), (b'ddMMyy', b'030806'), (b'ddMMyyyy', b'03082006'), (b'ddMMMyy', b'03Aug06'), (b'ddMMMyyyy', b'03Aug2006'), (b'dd-MMM-yy', b'03-Aug-06'), (b'dd-MMM-yyyy', b'03-Aug-2006'), (b'dMMMyy', b'3Aug06'), (b'dMMMyyyy', b'3Aug2006'), (b'd-MMM-yy', b'3-Aug-06'), (b'd-MMM-yyyy', b'3-Aug-2006'), (b'd-MMMM-yy', b'3-August-06'), (b'd-MMMM-yyyy', b'3-August-2006'), (b'yyMMdd', b'060803'), (b'yyyyMMdd', b'20060803'), (b'yy/MM/dd', b'06/08/03'), (b'yyyy/MM/dd', b'2006/08/03'), (b'MMddyyyy', b'08032006'), (b'MM/dd/yy', b'08/03/06'), (b'MM/dd/yyyy', b'08/03/2006'), (b'MMM-dd-yy', b'Aug-03-06'), (b'MMM-dd-yyyy', b'Aug-03-2006'), (b'yyyy-MM-dd', b'2006-08-03'), (b'dd-MM-yyyy', b'03-08-2006')], db_index=True, default=b'dd-MM-yyyy', max_length=15),
        ),
    ]
