# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_organizationsetting_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_department_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_department_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='employeedesignation',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_employeedesignation_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='employeedesignation',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_employeedesignation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_grouppermission_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_grouppermission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organization_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organization_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organizationsetting_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organizationsetting_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='person',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_person_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_person_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganization_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganization_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='personorganizationgrouppermission',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationgrouppermission_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='personorganizationgrouppermission',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationgrouppermission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
    ]
