# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20171019_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='bed_checkout_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
