# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20171020_1139'),
        ('core', '0026_organizationsetting_bed_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='service_consumed_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_transaction_head', to='account.TransactionHead'),
        ),
    ]
