# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20171020_1139'),
        ('core', '0027_organizationsetting_service_consumed_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='appointment_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_head', to='account.TransactionHead'),
        ),
    ]
