# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 05:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_person_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='economic_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Extreme Poor'), (1, b'Poor'), (2, b'Middle Class'), (3, b'Rich'), (4, b'Lower Middle Class')], db_index=True, default=1),
        ),
    ]
