# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 09:09
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20171110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='economic_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Extreme Poor'), (1, b'Poor'), (2, b'Lower Middle Class'), (3, b'Middle Class'), (4, b'Rich')], db_index=True, default=1),
        ),
    ]
