# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20171123_1545'),
        ('core', '0034_auto_20171123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='admission_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_head', to='account.TransactionHead'),
        ),
    ]
