# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_organizationsetting_admission_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
