# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20171207_1615'),
        ('core', '0036_personorganization_balance'),
    ]

    operations = [
    ]
