# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20171208_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name_font_size',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'h1'), (2, b'h2'), (3, b'h3'), (4, b'h4')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='print_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='print_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='print_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='print_slogan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='slogan_font_size',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'h1'), (2, b'h2'), (3, b'h3'), (4, b'h4')], db_index=True, default=3),
        ),
    ]
