# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20171212_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personorganization',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
