# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20171213_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='print_patient_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='print_patient_group',
            field=models.BooleanField(default=True),
        ),
    ]
