# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_organizationsetting_default_subservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='credit_limit',
            field=models.FloatField(default=0),
        ),
    ]
