# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_personorganization_credit_limit'),
        ('core', '0041_organizationsetting_patient_schedule_display'),
    ]

    operations = [
    ]
