# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20171222_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='patient_credit_limit',
            field=models.BooleanField(default=False),
        ),
    ]
