# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_organizationsetting_patient_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='appointment_schedules',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'patient appointment schedule'),
        ),
    ]
