# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_personorganization_appointment_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personorganization',
            options={'verbose_name': 'Person in Organization', 'verbose_name_plural': ('Person in Organizations',)},
        ),
        migrations.AlterIndexTogether(
            name='personorganization',
            index_together=set([('organization', 'person')]),
        ),
    ]
