# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20180112_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
    ]
