# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_organizationsetting_transaction_head_id'),
        ('core', '0049_personorganization_person_group'),
    ]

    operations = [
    ]
