# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20180116_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='display_patient_is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
