# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180123_1325'),
        ('core', '0052_organizationsetting_transaction_sms_feature'),
    ]

    operations = [
    ]
