# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180123_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personorganization',
            options={'verbose_name': 'Person in Organization', 'verbose_name_plural': 'Person in Organizations'},
        ),
    ]
