# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20180130_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriberDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriber_designation', to='core.EmployeeDesignation')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberdesignation_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization_settings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriber_organization_settings', to='core.OrganizationSetting')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberdesignation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='prescriber_designation',
            field=models.ManyToManyField(related_name='settings_prescriber_of_organization', through='core.PrescriberDesignation', to='core.EmployeeDesignation'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriberdesignation',
            unique_together=set([('organization_settings', 'employee_designation')]),
        ),
    ]
