# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20180130_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='trace_admission',
            field=models.BooleanField(default=False, help_text='Settings for trace admission'),
        ),
    ]
