# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organizationsetting_trace_admission'),
        ('core', '0060_auto_20180205_1354'),
    ]

    operations = [
    ]
