# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_merge_20180206_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriberdesignation',
            options={'verbose_name_plural': 'PrescriberDesignations'},
        ),
    ]
