# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20180209_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriberdesignation',
            options={'verbose_name_plural': 'Prescriber Designations'},
        ),
    ]
