# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20180213_1147'),
        ('core', '0060_auto_20180206_1718'),
    ]

    operations = [
    ]
