# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_20180216_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='family_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'-'), (1, b'Spouse'), (2, b'Son'), (3, b'Daughter'), (4, b'Son in law'), (5, b'Daughter in law'), (6, b'Father in law'), (7, b'Mother in law'), (8, b'Nice'), (9, b'Nephew'), (10, b'Uncle'), (11, b'Aunt')], db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_head_of_family',
            field=models.BooleanField(default=True, help_text='Whether this user should be treated as head of his family', verbose_name='head of family'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default=None, max_length=24, null=True, unique=True),
        ),
    ]
