# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20180320_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_duplicate_person_phone_no',
            field=models.BooleanField(default=True),
        ),
    ]
