# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20180320_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='country',
            field=models.CharField(choices=[(b'af', b'Afghanistan\t '), (b'al', b'Albania'), (b'dz', b'Algeria'), (b'as', b'American Samoa'), (b'ad', b'Andorra'), (b'ao', b'Angola'), (b'ai', b'Anguilla'), (b'aq', b'Antarctica'), (b'ag', b'Antigua and Barbuda'), (b'ar', b'Argentina'), (b'am', b'Armenia'), (b'aw', b'Aruba'), (b'ac', b'Ascension Island'), (b'au', b'Australia'), (b'at', b'Austria'), (b'az', b'Azerbaijan'), (b'bs', b'Bahamas'), (b'bh', b'Bahrain'), (b'bd', b'Bangladesh'), (b'bb', b'Barbados'), (b'by', b'Belarus'), (b'be', b'Belgium'), (b'bz', b'Belize'), (b'bj', b'Benin'), (b'bm', b'Bermuda'), (b'bt', b'Bhutan'), (b'bo', b'Bolivia'), (b'ba', b'Bosnia and Herzegovina'), (b'bw', b'Botswana'), (b'bv', b'Bouvet Island'), (b'br', b'Brazil'), (b'io', b'British Indian Ocean Territory'), (b'vg', b'British Virgin Islands'), (b'bn', b'Brunei Darussalam'), (b'bg', b'Bulgaria'), (b'bf', b'Burkina Faso'), (b'bi', b'Burundi'), (b'kh', b'Cambodia (Khmer)'), (b'cm', b'Cameroon'), (b'ca', b'Canada'), (b'cv', b'Cape Verde'), (b'ky', b'Cayman Islands'), (b'cf', b'Central African Republic'), (b'td', b'Chad'), (b'cl', b'Chile'), (b'cx', b'Christmas Island'), (b'cc', b'Cocos (Keeling) Islands'), (b'co', b'Colombia'), (b'km', b'Comoros'), (b'ck', b'Cook Islands'), (b'cr', b'Costa Rica'), (b'hr', b'Croatia (Hrvatska)'), (b'cu', b'Cuba'), (b'cy', b'Cyprus'), (b'cz', b'Czech Republic'), (b'ci', b"C\xc3\xb4te d'Ivoire"), (b'cd', b'Democratic Republic of the Congo (Formerly Zaire)'), (b'dk', b'Denmark'), (b'dj', b'Djibouti'), (b'dm', b'Dominica'), (b'do', b'Dominican Republic'), (b'tp', b'East Timor'), (b'ec', b'Ecuador'), (b'eg', b'Egypt'), (b'sv', b'El Salvador'), (b'gq', b'Equatorial Guinea'), (b'er', b'Eritrea'), (b'ee', b'Estonia'), (b'et', b'Ethiopia'), (b'eu', b'European Union'), (b'fk', b'Falkland Islands'), (b'fo', b'Faroe Islands'), (b'fm', b'Federated States of Micronesia'), (b'fj', b'Fiji'), (b'fi', b'Finland'), (b'fr', b'France'), (b'gf', b'French Guiana'), (b'pF', b'French Polynesia With Clipperton Island'), (b'tf', b'French Southern and Antarctic Lands'), (b'ga', b'Gabon'), (b'ge', b'Georgia'), (b'de', b'Germany (Deutschland)'), (b'gh', b'Ghana'), (b'gi', b'Gibraltar'), (b'gr', b'Greece'), (b'gl', b'Greenland'), (b'gd', b'Grenada'), (b'gp', b'Guadeloupe'), (b'gu', b'Guam'), (b'gt', b'Guatemala'), (b'gg', b'Guernsey'), (b'gn', b'Guinea'), (b'gw', b'Guinea-Bissau'), (b'gy', b'Guyana'), (b'ht', b'Haiti'), (b'hm', b'Heard Island and McDonald Islands'), (b'hn', b'Honduras'), (b'hk', b'Hong Kong'), (b'hu', b'Hungary'), (b'is', b'Iceland'), (b'in', b'India'), (b'id', b'Indonesia'), (b'ir', b'Iran'), (b'iq', b'Iraq'), (b'ie', b'Ireland'), (b'im', b'Isle of Man'), (b'il', b'Israel'), (b'it', b'Italy'), (b'jm', b'Jamaica'), (b'jp', b'Japan'), (b'je', b'Jersey'), (b'jo', b'Jordan'), (b'kz', b'Kazakhstan'), (b'ke', b'Kenya'), (b'ki', b'Kiribati'), (b'kw', b'Kuwait'), (b'kg', b'Kyrgyzstan'), (b'la', b'Laos'), (b'lv', b'Latvia'), (b'lb', b'Lebanon'), (b'ls', b'Lesotho'), (b'lr', b'Liberia'), (b'ly', b'Libya'), (b'li', b'Liechtenstein'), (b'lt', b'Lithuania'), (b'lu', b'Luxembourg'), (b'mo', b'Macau'), (b'mg', b'Madagascar'), (b'mW', b'Malawi'), (b'my', b'Malaysia'), (b'mv', b'Maldives'), (b'ml', b'Mali'), (b'mt', b'Malta'), (b'mh', b'Marshall Islands'), (b'mq', b'Martinique'), (b'mr', b'Mauritania'), (b'mu', b'Mauritius'), (b'yt', b'Mayotte'), (b'mx', b'Mexico'), (b'md', b'Moldova'), (b'mc', b'Monaco'), (b'mn', b'Mongolia'), (b'me', b'Montenegro'), (b'ms', b'Montserrat'), (b'ma', b'Morocco'), (b'mz', b'Mozambique'), (b'mm', b'Myanmar'), (b'na', b'Namibia'), (b'nr', b'Nauru'), (b'np', b'Nepal'), (b'nl', b'Netherlands'), (b'an', b'Netherlands Antilles'), (b'nc', b'New Caledonia'), (b'nz', b'New Zealand'), (b'ni', b'Nicaragua'), (b'ne', b'Niger'), (b'ng', b'Nigeria'), (b'nu', b'Niue'), (b'nF', b'Norfolk Island'), (b'mp', b'Northern Mariana Islands'), (b'no', b'Norway'), (b'om', b'Oman'), (b'pk', b'Pakistan'), (b'pw', b'Palau'), (b'ps', b'Palestinian territories\tie, West Bank and Gaza Strip'), (b'pa', b'Panama'), (b'pg', b'Papua New Guinea'), (b'py', b'Paraguay'), (b'cn', b"People's Republic of China"), (b'pe', b'Peru'), (b'ph', b'Philippines'), (b'pn', b'Pitcairn Islands'), (b'pl', b'Poland'), (b'pt', b'Portugal'), (b'pr', b'Puerto Rico'), (b'qa', b'Qatar'), (b'mk', b'Republic of Macedonia'), (b'cg', b'Republic of the Congo'), (b'ro', b'Romania'), (b'ru', b'Russia'), (b'rw', b'Rwanda'), (b're', b'R\xc3\xa9union'), (b'sh', b'Saint Helena'), (b'kn', b'Saint Kitts and Nevis'), (b'lc', b'Saint Lucia'), (b'vc', b'Saint Vincent and the Grenadines'), (b'pm', b'Saint-Pierre and Miquelon'), (b'ws', b'Samoa (Formerly Western Samoa)'), (b'sm', b'San Marino'), (b'sa', b'Saudi Arabia'), (b'sn', b'Senegal'), (b'rs', b'Serbia'), (b'sc', b'Seychelles'), (b'sl', b'Sierra Leone'), (b'sg', b'Singapore'), (b'sk', b'Slovakia'), (b'si', b'Slovenia'), (b'sb', b'Solomon Islands'), (b'so', b'Somalia'), (b'za', b'South Africa'), (b'gs', b'South Georgia and the South Sandwich Islands'), (b'kr', b'South Korea'), (b'su', b'Soviet Union'), (b'es', b'Spain (Espa\xc3\xb1a)'), (b'lk', b'Sri Lanka'), (b'sd', b'Sudan'), (b'sr', b'Suriname'), (b'sj', b'Svalbard and Jan Mayen Islands'), (b'sz', b'Swaziland'), (b'se', b'Sweden'), (b'ch', b'Switzerland'), (b'sy', b'Syria'), (b'st', b'S\xc3\xa3o Tom\xc3\xa9 and Pr\xc3\xadncipe'), (b'tw', b'Taiwan'), (b'tj', b'Tajikistan'), (b'tz', b'Tanzania'), (b'th', b'Thailand'), (b'gm', b'The Gambia'), (b'tl', b'Timor-Leste'), (b'tg', b'Togo'), (b'tk', b'Tokelau'), (b'to', b'Tonga'), (b'tt', b'Trinidad and Tobago'), (b'tn', b'Tunisia'), (b'tr', b'Turkey'), (b'tm', b'Turkmenistan'), (b'tc', b'Turks and Caicos Islands'), (b'tv', b'Tuvalu'), (b'vi', b'US Virgin Islands'), (b'ug', b'Uganda'), (b'ua', b'Ukraine'), (b'ae', b'United Arab Emirates'), (b'gb', b'United Kingdom'), (b'uk', b'United Kingdom'), (b'um', b'United States Minor Outlying Islands'), (b'us', b'United States of America'), (b'uy', b'Uruguay'), (b'uz', b'Uzbekistan'), (b'vu', b'Vanuatu'), (b'va', b'Vatican City State'), (b've', b'Venezuela'), (b'vn', b'Vietnam'), (b'wf', b'Wallis and Futuna'), (b'ye', b'Yemen'), (b'yu', b'Yugoslavia'), (b'zm', b'Zambia'), (b'zw', b'Zimbabwe')], db_index=True, default=b'bd', max_length=2),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='degree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.EmployeeDesignation'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='economic_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Extreme Poor'), (1, b'Poor'), (2, b'Middle Class'), (3, b'Rich'), (4, b'Lower Middle Class'), (5, b'Upper Middle class'), (6, b'Emergency')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='family_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'-'), (1, b'Spouse'), (2, b'Son'), (3, b'Daughter'), (4, b'Son in law'), (5, b'Daughter in law'), (6, b'Father in law'), (7, b'Mother in law'), (8, b'Nice'), (9, b'Nephew'), (10, b'Uncle'), (11, b'Aunt')], db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='gender',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Transsexual'), (3, b'Any')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='language',
            field=models.CharField(choices=[(b'bn', b'Bangla'), (b'en', b'English')], default=b'en', max_length=2),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='medical_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='patient_refered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='phone',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='present_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='relatives_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='relatives_contact_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='relatives_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='relatives_relation',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Father'), (1, b'Mother'), (2, b'Spouse'), (3, b'Brother'), (4, b'Sister'), (5, b'Uncle'), (6, b'Aunt'), (7, b'Brother in Law'), (8, b'Sister in Law'), (9, b'Father in Law'), (10, b'Friends'), (11, b'Helping Hand'), (99, b'Other')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
