# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180323_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'-'), (1, b'Spouse'), (2, b'Son'), (3, b'Daughter'), (4, b'Son in law'), (5, b'Daughter in law'), (6, b'Father in law'), (7, b'Mother in law'), (8, b'Niece'), (9, b'Nephew'), (10, b'Uncle'), (11, b'Aunt'), (12, b'Head'), (13, b'Other')], db_index=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_head_of_family',
            field=models.BooleanField(default=False, help_text='Whether this user should be treated as head of his family', verbose_name='head of family'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'-'), (1, b'Spouse'), (2, b'Son'), (3, b'Daughter'), (4, b'Son in law'), (5, b'Daughter in law'), (6, b'Father in law'), (7, b'Mother in law'), (8, b'Niece'), (9, b'Nephew'), (10, b'Uncle'), (11, b'Aunt'), (12, b'Head'), (13, b'Other')], db_index=True, default=None, null=True),
        ),
    ]
