# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0047_auto_20180327_1521'),
        ('clinic', '0083_auto_20180327_1521'),
        ('account', '0044_merge_20180327_1124'),
        ('core', '0068_auto_20180327_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrganizationDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('remarks', models.CharField(blank=True, max_length=128)),
                ('discount_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discount_by', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationdiscount_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('on_request_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='on_request_discount', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name')),
                ('person_organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons_organization_discount', to='core.PersonOrganization')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases_discount', to='pharmacy.Purchase')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_discount', to='pharmacy.Sales')),
                ('service_consumed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_consumed_discount', to='clinic.ServiceConsumed')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_discount', to='account.Transaction')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationdiscount_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name': 'Person Discount in Organization',
                'verbose_name_plural': 'Person Discount in Organizations',
            },
        ),
        migrations.AlterIndexTogether(
            name='personorganizationdiscount',
            index_together=set([('organization', 'person_organization')]),
        ),
    ]
