# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20180327_1231'),
        ('core', '0067_organizationsetting_allow_duplicate_person_phone_no'),
    ]

    operations = [
    ]
