# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_organizationsetting_allow_service_consumed_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
