# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_personorganization_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
