# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_personorganization_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personorganization',
            name='is_dead',
        ),
        migrations.AddField(
            model_name='personorganization',
            name='dropout_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='dropout_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Dead'), (3, b'Move to another organization')], db_index=True, default=1),
        ),
    ]
