# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_personorganization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='fingerprint_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fingerprint_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fingerprint_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
