# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0050_auto_20180412_0732'),
        ('core', '0073_auto_20180419_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_storepoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.StorePoint'),
        ),
    ]
