# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_merge_20180420_0645'),
        ('core', '0074_organizationsetting_default_storepoint'),
    ]

    operations = [
    ]
