# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0097_auto_20180424_1026'),
        ('core', '0075_merge_20180423_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='joining_initiator',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Sales'), (2, b'Service')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='joining_initiator_sub_service',
            field=models.ForeignKey(blank=True, help_text='select sub-service for joining date', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_service_for_joining_date', to='clinic.SubService'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='default_subservice',
            field=models.ForeignKey(blank=True, help_text='select sub-service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_service_for_default_service', to='clinic.SubService'),
        ),
    ]
