# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 09:46
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20180427_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pagination_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Scroll')], db_index=True, default=1),
        ),
    ]
