# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_person_pagination_type'),
        ('core', '0069_auto_20180328_1022'),
    ]

    operations = [
    ]
