# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_personorganization_country_code'),
        ('core', '0078_merge_20180511_0942'),
    ]

    operations = [
    ]
