# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_merge_20180511_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='fingerprint_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='fingerprint_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='fingerprint_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
