# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_organizationsetting_product_vat_tax_status'),
        ('core', '0080_person_date_picker'),
    ]

    operations = [
    ]
