# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20180511_1048'),
        ('core', '0081_merge_20180525_0328'),
    ]

    operations = [
    ]
