# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_merge_20180525_0328'),
        ('core', '0077_auto_20180510_0812'),
    ]

    operations = [
    ]
