# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_merge_20180530_0943'),
        ('core', '0082_merge_20180529_0643'),
    ]

    operations = [
    ]
