# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_organizationsetting_service_consumed_print_type'),
        ('core', '0083_merge_20180605_0627'),
    ]

    operations = [
    ]
