# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_patientbill'),
        ('core', '0084_merge_20180606_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_cashpoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_default_cash_point', to='account.Accounts'),
        ),
    ]
