# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0058_auto_20180619_0847'),
        ('core', '0085_organizationsetting_default_cashpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='product_as_tube',
            field=models.ForeignKey(blank=True, help_text='Choose a default product for using as tube', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tube_product', to='pharmacy.Product'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='tube_in_diagnostic_sample',
            field=models.BooleanField(default=False, help_text='allow tube for taking samples'),
        ),
    ]
