# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20180620_1243'),
        ('core', '0087_merge_20180621_0842'),
    ]

    operations = [
    ]
