# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20180626_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='husbands_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
