# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 10:54
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20180702_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='birth_id',
            field=models.CharField(blank=True, help_text='Birth ID No. Example: YYYYXXXXXXXXXXXXX', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='hero_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to=b'profiles/hero'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='nid',
            field=models.CharField(blank=True, default=None, help_text='National ID No. Example: YYYYXXXXXXXXXXXXX', max_length=32, null=True, verbose_name='NID No.'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='profile_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to=b'profiles/pic'),
        ),
    ]
