# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_organizationsetting_secondary_referrer_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='show_patient_age',
            field=models.BooleanField(default=False, help_text='Show patient age'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='show_patient_economic_status',
            field=models.BooleanField(default=False, help_text='Show patient economic status'),
        ),
    ]
