# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20180709_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='referrer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ReferrerCategory'),
        ),
    ]
