# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_personorganization_referrer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='show_referrer_honorarium',
            field=models.BooleanField(default=False, help_text='Show referrer honorarium'),
        ),
    ]
