# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_organizationsetting_show_referrer_honorarium'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='copies_while_print',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_label_appointment_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_label_consumed_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_label_sales_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_label_transaction_print',
            field=models.BooleanField(default=False),
        ),
    ]
