# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20180802_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='print_page_header',
            field=models.BooleanField(default=True),
        ),
    ]
