# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 08:12
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20180802_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from=b'name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_global', enumerify.fields.SelectIntegerField(choices=[(0, b'Private'), (1, b'Global'), (2, b'Changed into Global')], db_index=True, default=0)),
                ('group_type', enumerify.fields.SelectIntegerField(choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other')], db_index=True, default=0)),
                ('clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PersonGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by'),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name=b'organization name'),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by'),
        ),
        migrations.AddField(
            model_name='person',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_belongs_to', to='core.PersonGroup'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_in_organization_belongs_to', to='core.PersonGroup'),
        ),
    ]
