# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_organizationsetting_print_page_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='print_test_name',
            field=models.BooleanField(default=True, help_text='Show / Hide Test Name in Print'),
        ),
    ]
