# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_discountgroup'),
        ('core', '0098_auto_20180802_0812'),
    ]

    operations = [
    ]
