# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_merge_20180816_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriberReferrerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Draft'), (3, b'Released'), (4, b'Approved Draft'), (5, b'Absent'), (6, b'Purchase Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberreferrercategory_entry_by', to=settings.AUTH_USER_MODEL, verbose_name=b'entry by')),
                ('organization_settings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriber_referrer_category_organization_setting', to='core.OrganizationSetting')),
                ('referrer_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriber_referrer_category', to='core.ReferrerCategory')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberreferrercategory_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'last updated by')),
            ],
            options={
                'verbose_name_plural': 'Prescriber Referrer Categories',
            },
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='prescriber_referrer_category',
            field=models.ManyToManyField(related_name='settings_prescriber_referrer_category', through='core.PrescriberReferrerCategory', to='core.ReferrerCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriberreferrercategory',
            unique_together=set([('organization_settings', 'referrer_category')]),
        ),
    ]
