# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20180803_0631'),
        ('core', '0103_auto_20180827_0759'),
    ]

    operations = [
    ]
