# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 13:32
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20180827_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Mother'), (1, b'Branch'), (2, b'Unite'), (3, b'Private Practitioners'), (4, b'Pharmacy'), (5, b'Diagnostic')], db_index=True, default=0),
        ),
    ]
