# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20180830_0931'),
        ('core', '0104_auto_20180830_1332'),
    ]

    operations = [
    ]
