# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_organizationsetting_auto_adjustment'),
        ('core', '0107_organization_show_global_product'),
    ]

    operations = [
    ]
