# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 07:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_merge_20180925_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='discount_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Flat'), (2, b'Percentage')], db_index=True, default=1, help_text='Choose Discount type'),
        ),
    ]
