# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_merge_20180925_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganizationsalary',
            name='others_addition',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personorganizationsalary',
            name='others_deduction',
            field=models.FloatField(default=0.0),
        ),
    ]
