# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_organizationsetting_discount_type'),
        ('core', '0109_auto_20180928_0335'),
    ]

    operations = [
    ]
