# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_personorganization_diagnosis_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='show_dependency_disease',
            field=models.BooleanField(default=False),
        ),
    ]
