# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_organizationsetting_show_dependency_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_generic_name',
            field=models.BooleanField(default=False, help_text='Show / Hide Generic Name in item dropdown'),
        ),
        migrations.AddField(
            model_name='person',
            name='show_group_name',
            field=models.BooleanField(default=False, help_text='Show / Hide Group Name in item dropdown'),
        ),
        migrations.AddField(
            model_name='person',
            name='show_item_in_one_line',
            field=models.BooleanField(default=False, help_text='Show/ Hide item details in one line in item dropdown'),
        ),
        migrations.AddField(
            model_name='person',
            name='show_subgroup_name',
            field=models.BooleanField(default=False, help_text='Show/ Hide SubGroup Name in item dropdown'),
        ),
    ]
