# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20181030_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='show_purchase_price',
            field=models.BooleanField(default=False, help_text='Settings for show purchase price as suggestion'),
        ),
    ]
