# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_organizationsetting_show_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_multiple_unit',
            field=models.BooleanField(default=False, help_text='Settings for enable multiple unit in purchase io panel'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='sales_multiple_unit',
            field=models.BooleanField(default=False, help_text='Settings for enable multiple unit in sales io panel'),
        ),
    ]
