# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20181102_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='purchase_multiple_unit',
            field=models.BooleanField(default=True, help_text='Settings for enable multiple unit in purchase io panel'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='sales_multiple_unit',
            field=models.BooleanField(default=True, help_text='Settings for enable multiple unit in sales io panel'),
        ),
    ]
