# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20181107_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_discount_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='default_vat_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
