# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 05:19
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20181114_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='price_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Latest Price'), (2, b'Product Price'), (3, b'Latest Price and Product Price'), (4, b'Product Price and Latest Price')], db_index=True, default=1, help_text='Choose which price to show'),
        ),
    ]
