# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 07:09
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_organizationsetting_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='theme',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Light'), (1, b'Dark')], db_index=True, default=1),
        ),
    ]
