# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0090_auto_20181213_1116'),
        ('account', '0058_auto_20181114_1224'),
        ('core', '0121_auto_20181206_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='default_cashpoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization_of_account', to='account.Accounts'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='default_storepoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization_of_store', to='pharmacy.StorePoint'),
        ),
    ]
