# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20181214_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='bar_code',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable bar code'),
        ),
    ]
