# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_organizationsetting_bar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='transaction_receipt_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
