# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_organization_transaction_receipt_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='multiple_payment',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable multiple payment'),
        ),
    ]
