# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 07:47
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20190201_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='service_consumed_receipt_type',
            field=enumerify.fields.SelectIntegerField(default=2, help_text='Service Consumed Receipt Type'),
        ),
    ]
