# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20190201_1334'),
        ('core', '0129_organizationsetting_service_consumed_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_return_head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_return_transaction_head', to='account.TransactionHead'),
        ),
    ]
