# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20190219_1233'),
        ('core', '0130_organizationsetting_purchase_return_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discarded_heads',
            field=models.ManyToManyField(related_name='organization_of_discarded_head', through='account.OrganizationWiseDiscardedTransactionHead', to='account.TransactionHead'),
        ),
    ]
