# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 13:00
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_organization_discarded_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='salary_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Basic From Gross'), (2, b'Gross From Basic')], db_index=True, default=1, help_text='Choose for Salary type'),
        ),
    ]
