# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20190328_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='salary_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_org_salary_grade', to='core.SalaryGrade'),
        ),
    ]
