# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_organization_discarded_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_offline',
            field=models.BooleanField(default=True, help_text='Settings for enable/disable offline'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='offline_sales_number',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
