# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 04:37
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20190521_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='global_product_category',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'GPA'), (3, b'GPB')], db_index=True, default=1),
        ),
    ]
