# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 06:09
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20190527_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='package',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Package 1'), (2, b'Package 2'), (3, b'Package 3')], db_index=True, default=3, help_text='Define different packages for client'),
        ),
    ]
