# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_organizationsetting_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='allow_offline',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable offline'),
        ),
    ]
