# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20190620_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='negative_stock',
            field=models.IntegerField(default=0),
        ),
    ]
