# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20190725_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_discount_margin',
            field=models.BooleanField(default=False, help_text="Settings for enable/disable stock's discount Margin"),
        ),
    ]
