# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 13:09
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_organizationsetting_allow_sale_rate_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='patient_info_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'SHORT'), (2, b'DETAILS')], db_index=True, default=1),
        ),
    ]
