# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 06:43
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_organizationsetting_patient_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Internal'), (2, b'External')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='person_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Internal'), (2, b'External')], db_index=True, default=1),
        ),
    ]
