# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 12:31
from __future__ import unicode_literals

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20190827_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other'), (9, b'Prescriber')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='group_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other'), (9, b'Prescriber')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, b'Patient'), (1, b'Employee'), (2, b'Stack Holder'), (3, b'Supplier'), (4, b'Board of Director'), (5, b'System Admin'), (6, b'Referrer'), (7, b'Service Provider'), (8, b'Other'), (9, b'Prescriber')], db_index=True, default=0, null=True),
        ),
    ]
