# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20190829_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='allow_purchase_default_discount_vat_rate',
            field=models.BooleanField(default=True, help_text='Settings for allowing purchase default discount and vat rate in io operation'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_bar_code',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable Purchase bar code'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_default_discount_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_default_vat_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_discount_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Flat'), (2, b'Percentage')], db_index=True, default=1, help_text='Choices for Purchase Discount type'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_price_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Latest Price'), (2, b'Product Price'), (3, b'Latest Price and Product Price'), (4, b'Product Price and Latest Price')], db_index=True, default=1, help_text='Choices for Purchase price type to show'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_product_vat_discount_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, b'Default'), (2, b'Product Wise')], db_index=True, default=1, help_text='Choices for purchase product show individual vat, tax and discount or not'),
        ),
    ]
