# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20190902_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personorganizationgrouppermission',
            name='person_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_permission', to='core.PersonOrganization'),
        ),
    ]
