# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20190902_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_referrer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_of_organization', to='core.ReferrerCategory'),
        ),
    ]
