# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_organizationsetting_default_referrer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='whole_sale',
            field=models.BooleanField(default=False),
        ),
    ]
