# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 11:46
from __future__ import unicode_literals

import autoslug.fields
import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_organizationsetting_whole_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_department_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_department_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_discountgroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_discountgroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_employeedesignation_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_employeedesignation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_grouppermission_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_grouppermission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organization_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='organization/logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_font_size',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'h1'), (2, 'h2'), (3, 'h3'), (4, 'h4')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slogan_font_size',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'h1'), (2, 'h2'), (3, 'h3'), (4, 'h4')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Mother'), (1, 'Branch'), (2, 'Unite'), (3, 'Private Practitioners'), (4, 'Pharmacy'), (5, 'Diagnostic')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organization_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='data_entry_mode',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'ON'), (2, 'OFF'), (3, 'DONE')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='date_format',
            field=models.CharField(choices=[('dd/MM/yy', '03/08/06'), ('dd/MM/yyyy', '03/08/2006'), ('d/M/yy', '3/8/06'), ('d/M/yyyy', '3/8/2006'), ('ddMMyy', '030806'), ('ddMMyyyy', '03082006'), ('ddMMMyy', '03Aug06'), ('ddMMMyyyy', '03Aug2006'), ('dd-MMM-yy', '03-Aug-06'), ('dd-MMM-yyyy', '03-Aug-2006'), ('dMMMyy', '3Aug06'), ('dMMMyyyy', '3Aug2006'), ('d-MMM-yy', '3-Aug-06'), ('d-MMM-yyyy', '3-Aug-2006'), ('d-MMMM-yy', '3-August-06'), ('d-MMMM-yyyy', '3-August-2006'), ('yyMMdd', '060803'), ('yyyyMMdd', '20060803'), ('yy/MM/dd', '06/08/03'), ('yyyy/MM/dd', '2006/08/03'), ('MMddyyyy', '08032006'), ('MM/dd/yy', '08/03/06'), ('MM/dd/yyyy', '08/03/2006'), ('MMM-dd-yy', 'Aug-03-06'), ('MMM-dd-yyyy', 'Aug-03-2006'), ('yyyy-MM-dd', '2006-08-03'), ('dd-MM-yyyy', '03-08-2006')], db_index=True, default='dd-MM-yyyy', max_length=15),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='discount_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Flat'), (2, 'Percentage')], db_index=True, default=1, help_text='Choose Discount type'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organizationsetting_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='global_product_category',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'GPA'), (3, 'GPB')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='joining_initiator',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Sales'), (2, 'Service')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='package',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Package 1'), (2, 'Package 2'), (3, 'Package 3')], db_index=True, default=3, help_text='Define different packages for client'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='patient_code_prefix',
            field=models.CharField(default='OMIS', max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='patient_info_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'SHORT'), (2, 'DETAILS')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='price_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Latest Price'), (2, 'Product Price'), (3, 'Latest Price and Product Price'), (4, 'Product Price and Latest Price')], db_index=True, default=1, help_text='Choose which price to show'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='print_configuration',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Sweet Alert Off'), (2, 'Sweet Alert On')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='product_vat_tax_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Product Wise')], db_index=True, default=1, help_text='Choices for product show individual vat, tax and discount or not'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='purchase_discount_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Flat'), (2, 'Percentage')], db_index=True, default=1, help_text='Choices for Purchase Discount type'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='purchase_price_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Latest Price'), (2, 'Product Price'), (3, 'Latest Price and Product Price'), (4, 'Product Price and Latest Price')], db_index=True, default=1, help_text='Choices for Purchase price type to show'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='purchase_product_vat_discount_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Product Wise')], db_index=True, default=1, help_text='Choices for purchase product show individual vat, tax and discount or not'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='salary_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Basic From Gross'), (2, 'Gross From Basic')], db_index=True, default=1, help_text='Choose for Salary type'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='serial_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Organization Wise'), (3, 'No Serial')], db_index=True, default=1, help_text='Choose Serial/ID type'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='service_consumed_print_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Service Consumed Receipt')], db_index=True, default=1, help_text='Choose service consumed print type'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_organizationsetting_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(choices=[('af', 'Afghanistan\t '), ('al', 'Albania'), ('dz', 'Algeria'), ('as', 'American Samoa'), ('ad', 'Andorra'), ('ao', 'Angola'), ('ai', 'Anguilla'), ('aq', 'Antarctica'), ('ag', 'Antigua and Barbuda'), ('ar', 'Argentina'), ('am', 'Armenia'), ('aw', 'Aruba'), ('ac', 'Ascension Island'), ('au', 'Australia'), ('at', 'Austria'), ('az', 'Azerbaijan'), ('bs', 'Bahamas'), ('bh', 'Bahrain'), ('bd', 'Bangladesh'), ('bb', 'Barbados'), ('by', 'Belarus'), ('be', 'Belgium'), ('bz', 'Belize'), ('bj', 'Benin'), ('bm', 'Bermuda'), ('bt', 'Bhutan'), ('bo', 'Bolivia'), ('ba', 'Bosnia and Herzegovina'), ('bw', 'Botswana'), ('bv', 'Bouvet Island'), ('br', 'Brazil'), ('io', 'British Indian Ocean Territory'), ('vg', 'British Virgin Islands'), ('bn', 'Brunei Darussalam'), ('bg', 'Bulgaria'), ('bf', 'Burkina Faso'), ('bi', 'Burundi'), ('kh', 'Cambodia (Khmer)'), ('cm', 'Cameroon'), ('ca', 'Canada'), ('cv', 'Cape Verde'), ('ky', 'Cayman Islands'), ('cf', 'Central African Republic'), ('td', 'Chad'), ('cl', 'Chile'), ('cx', 'Christmas Island'), ('cc', 'Cocos (Keeling) Islands'), ('co', 'Colombia'), ('km', 'Comoros'), ('ck', 'Cook Islands'), ('cr', 'Costa Rica'), ('hr', 'Croatia (Hrvatska)'), ('cu', 'Cuba'), ('cy', 'Cyprus'), ('cz', 'Czech Republic'), ('ci', "Côte d'Ivoire"), ('cd', 'Democratic Republic of the Congo (Formerly Zaire)'), ('dk', 'Denmark'), ('dj', 'Djibouti'), ('dm', 'Dominica'), ('do', 'Dominican Republic'), ('tp', 'East Timor'), ('ec', 'Ecuador'), ('eg', 'Egypt'), ('sv', 'El Salvador'), ('gq', 'Equatorial Guinea'), ('er', 'Eritrea'), ('ee', 'Estonia'), ('et', 'Ethiopia'), ('eu', 'European Union'), ('fk', 'Falkland Islands'), ('fo', 'Faroe Islands'), ('fm', 'Federated States of Micronesia'), ('fj', 'Fiji'), ('fi', 'Finland'), ('fr', 'France'), ('gf', 'French Guiana'), ('pF', 'French Polynesia With Clipperton Island'), ('tf', 'French Southern and Antarctic Lands'), ('ga', 'Gabon'), ('ge', 'Georgia'), ('de', 'Germany (Deutschland)'), ('gh', 'Ghana'), ('gi', 'Gibraltar'), ('gr', 'Greece'), ('gl', 'Greenland'), ('gd', 'Grenada'), ('gp', 'Guadeloupe'), ('gu', 'Guam'), ('gt', 'Guatemala'), ('gg', 'Guernsey'), ('gn', 'Guinea'), ('gw', 'Guinea-Bissau'), ('gy', 'Guyana'), ('ht', 'Haiti'), ('hm', 'Heard Island and McDonald Islands'), ('hn', 'Honduras'), ('hk', 'Hong Kong'), ('hu', 'Hungary'), ('is', 'Iceland'), ('in', 'India'), ('id', 'Indonesia'), ('ir', 'Iran'), ('iq', 'Iraq'), ('ie', 'Ireland'), ('im', 'Isle of Man'), ('il', 'Israel'), ('it', 'Italy'), ('jm', 'Jamaica'), ('jp', 'Japan'), ('je', 'Jersey'), ('jo', 'Jordan'), ('kz', 'Kazakhstan'), ('ke', 'Kenya'), ('ki', 'Kiribati'), ('kw', 'Kuwait'), ('kg', 'Kyrgyzstan'), ('la', 'Laos'), ('lv', 'Latvia'), ('lb', 'Lebanon'), ('ls', 'Lesotho'), ('lr', 'Liberia'), ('ly', 'Libya'), ('li', 'Liechtenstein'), ('lt', 'Lithuania'), ('lu', 'Luxembourg'), ('mo', 'Macau'), ('mg', 'Madagascar'), ('mW', 'Malawi'), ('my', 'Malaysia'), ('mv', 'Maldives'), ('ml', 'Mali'), ('mt', 'Malta'), ('mh', 'Marshall Islands'), ('mq', 'Martinique'), ('mr', 'Mauritania'), ('mu', 'Mauritius'), ('yt', 'Mayotte'), ('mx', 'Mexico'), ('md', 'Moldova'), ('mc', 'Monaco'), ('mn', 'Mongolia'), ('me', 'Montenegro'), ('ms', 'Montserrat'), ('ma', 'Morocco'), ('mz', 'Mozambique'), ('mm', 'Myanmar'), ('na', 'Namibia'), ('nr', 'Nauru'), ('np', 'Nepal'), ('nl', 'Netherlands'), ('an', 'Netherlands Antilles'), ('nc', 'New Caledonia'), ('nz', 'New Zealand'), ('ni', 'Nicaragua'), ('ne', 'Niger'), ('ng', 'Nigeria'), ('nu', 'Niue'), ('nF', 'Norfolk Island'), ('mp', 'Northern Mariana Islands'), ('no', 'Norway'), ('om', 'Oman'), ('pk', 'Pakistan'), ('pw', 'Palau'), ('ps', 'Palestinian territories\tie, West Bank and Gaza Strip'), ('pa', 'Panama'), ('pg', 'Papua New Guinea'), ('py', 'Paraguay'), ('cn', "People's Republic of China"), ('pe', 'Peru'), ('ph', 'Philippines'), ('pn', 'Pitcairn Islands'), ('pl', 'Poland'), ('pt', 'Portugal'), ('pr', 'Puerto Rico'), ('qa', 'Qatar'), ('mk', 'Republic of Macedonia'), ('cg', 'Republic of the Congo'), ('ro', 'Romania'), ('ru', 'Russia'), ('rw', 'Rwanda'), ('re', 'Réunion'), ('sh', 'Saint Helena'), ('kn', 'Saint Kitts and Nevis'), ('lc', 'Saint Lucia'), ('vc', 'Saint Vincent and the Grenadines'), ('pm', 'Saint-Pierre and Miquelon'), ('ws', 'Samoa (Formerly Western Samoa)'), ('sm', 'San Marino'), ('sa', 'Saudi Arabia'), ('sn', 'Senegal'), ('rs', 'Serbia'), ('sc', 'Seychelles'), ('sl', 'Sierra Leone'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('sb', 'Solomon Islands'), ('so', 'Somalia'), ('za', 'South Africa'), ('gs', 'South Georgia and the South Sandwich Islands'), ('kr', 'South Korea'), ('su', 'Soviet Union'), ('es', 'Spain (España)'), ('lk', 'Sri Lanka'), ('sd', 'Sudan'), ('sr', 'Suriname'), ('sj', 'Svalbard and Jan Mayen Islands'), ('sz', 'Swaziland'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('sy', 'Syria'), ('st', 'São Tomé and Príncipe'), ('tw', 'Taiwan'), ('tj', 'Tajikistan'), ('tz', 'Tanzania'), ('th', 'Thailand'), ('gm', 'The Gambia'), ('tl', 'Timor-Leste'), ('tg', 'Togo'), ('tk', 'Tokelau'), ('to', 'Tonga'), ('tt', 'Trinidad and Tobago'), ('tn', 'Tunisia'), ('tr', 'Turkey'), ('tm', 'Turkmenistan'), ('tc', 'Turks and Caicos Islands'), ('tv', 'Tuvalu'), ('vi', 'US Virgin Islands'), ('ug', 'Uganda'), ('ua', 'Ukraine'), ('ae', 'United Arab Emirates'), ('gb', 'United Kingdom'), ('uk', 'United Kingdom'), ('um', 'United States Minor Outlying Islands'), ('us', 'United States of America'), ('uy', 'Uruguay'), ('uz', 'Uzbekistan'), ('vu', 'Vanuatu'), ('va', 'Vatican City State'), ('ve', 'Venezuela'), ('vn', 'Vietnam'), ('wf', 'Wallis and Futuna'), ('ye', 'Yemen'), ('yu', 'Yugoslavia'), ('zm', 'Zambia'), ('zw', 'Zimbabwe')], db_index=True, default='bd', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_picker',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Default Date Picker'), (2, 'Give In Year')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='economic_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Extreme Poor'), (1, 'Poor'), (2, 'Middle Class'), (3, 'Rich'), (4, 'Lower Middle Class'), (5, 'Upper Middle class'), (6, 'Emergency')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_person_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, '-'), (1, 'Spouse'), (2, 'Son'), (3, 'Daughter'), (4, 'Son in law'), (5, 'Daughter in law'), (6, 'Father in law'), (7, 'Mother in law'), (8, 'Niece'), (9, 'Nephew'), (10, 'Uncle'), (11, 'Aunt'), (12, 'Head'), (13, 'Other')], db_index=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Transsexual'), (3, 'Any')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='hero_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='profiles/hero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pagination_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Scroll')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Internal'), (2, 'External')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='profiles/pic'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relatives_relation',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Father'), (1, 'Mother'), (2, 'Spouse'), (3, 'Brother'), (4, 'Sister'), (5, 'Uncle'), (6, 'Aunt'), (7, 'Brother in Law'), (8, 'Sister in Law'), (9, 'Father in Law'), (10, 'Friends'), (11, 'Helping Hand'), (99, 'Other')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='theme',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Light'), (1, 'Dark')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_person_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='group_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_persongroup_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='appointment_schedules',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='patient appointment schedule'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='country',
            field=models.CharField(choices=[('af', 'Afghanistan\t '), ('al', 'Albania'), ('dz', 'Algeria'), ('as', 'American Samoa'), ('ad', 'Andorra'), ('ao', 'Angola'), ('ai', 'Anguilla'), ('aq', 'Antarctica'), ('ag', 'Antigua and Barbuda'), ('ar', 'Argentina'), ('am', 'Armenia'), ('aw', 'Aruba'), ('ac', 'Ascension Island'), ('au', 'Australia'), ('at', 'Austria'), ('az', 'Azerbaijan'), ('bs', 'Bahamas'), ('bh', 'Bahrain'), ('bd', 'Bangladesh'), ('bb', 'Barbados'), ('by', 'Belarus'), ('be', 'Belgium'), ('bz', 'Belize'), ('bj', 'Benin'), ('bm', 'Bermuda'), ('bt', 'Bhutan'), ('bo', 'Bolivia'), ('ba', 'Bosnia and Herzegovina'), ('bw', 'Botswana'), ('bv', 'Bouvet Island'), ('br', 'Brazil'), ('io', 'British Indian Ocean Territory'), ('vg', 'British Virgin Islands'), ('bn', 'Brunei Darussalam'), ('bg', 'Bulgaria'), ('bf', 'Burkina Faso'), ('bi', 'Burundi'), ('kh', 'Cambodia (Khmer)'), ('cm', 'Cameroon'), ('ca', 'Canada'), ('cv', 'Cape Verde'), ('ky', 'Cayman Islands'), ('cf', 'Central African Republic'), ('td', 'Chad'), ('cl', 'Chile'), ('cx', 'Christmas Island'), ('cc', 'Cocos (Keeling) Islands'), ('co', 'Colombia'), ('km', 'Comoros'), ('ck', 'Cook Islands'), ('cr', 'Costa Rica'), ('hr', 'Croatia (Hrvatska)'), ('cu', 'Cuba'), ('cy', 'Cyprus'), ('cz', 'Czech Republic'), ('ci', "Côte d'Ivoire"), ('cd', 'Democratic Republic of the Congo (Formerly Zaire)'), ('dk', 'Denmark'), ('dj', 'Djibouti'), ('dm', 'Dominica'), ('do', 'Dominican Republic'), ('tp', 'East Timor'), ('ec', 'Ecuador'), ('eg', 'Egypt'), ('sv', 'El Salvador'), ('gq', 'Equatorial Guinea'), ('er', 'Eritrea'), ('ee', 'Estonia'), ('et', 'Ethiopia'), ('eu', 'European Union'), ('fk', 'Falkland Islands'), ('fo', 'Faroe Islands'), ('fm', 'Federated States of Micronesia'), ('fj', 'Fiji'), ('fi', 'Finland'), ('fr', 'France'), ('gf', 'French Guiana'), ('pF', 'French Polynesia With Clipperton Island'), ('tf', 'French Southern and Antarctic Lands'), ('ga', 'Gabon'), ('ge', 'Georgia'), ('de', 'Germany (Deutschland)'), ('gh', 'Ghana'), ('gi', 'Gibraltar'), ('gr', 'Greece'), ('gl', 'Greenland'), ('gd', 'Grenada'), ('gp', 'Guadeloupe'), ('gu', 'Guam'), ('gt', 'Guatemala'), ('gg', 'Guernsey'), ('gn', 'Guinea'), ('gw', 'Guinea-Bissau'), ('gy', 'Guyana'), ('ht', 'Haiti'), ('hm', 'Heard Island and McDonald Islands'), ('hn', 'Honduras'), ('hk', 'Hong Kong'), ('hu', 'Hungary'), ('is', 'Iceland'), ('in', 'India'), ('id', 'Indonesia'), ('ir', 'Iran'), ('iq', 'Iraq'), ('ie', 'Ireland'), ('im', 'Isle of Man'), ('il', 'Israel'), ('it', 'Italy'), ('jm', 'Jamaica'), ('jp', 'Japan'), ('je', 'Jersey'), ('jo', 'Jordan'), ('kz', 'Kazakhstan'), ('ke', 'Kenya'), ('ki', 'Kiribati'), ('kw', 'Kuwait'), ('kg', 'Kyrgyzstan'), ('la', 'Laos'), ('lv', 'Latvia'), ('lb', 'Lebanon'), ('ls', 'Lesotho'), ('lr', 'Liberia'), ('ly', 'Libya'), ('li', 'Liechtenstein'), ('lt', 'Lithuania'), ('lu', 'Luxembourg'), ('mo', 'Macau'), ('mg', 'Madagascar'), ('mW', 'Malawi'), ('my', 'Malaysia'), ('mv', 'Maldives'), ('ml', 'Mali'), ('mt', 'Malta'), ('mh', 'Marshall Islands'), ('mq', 'Martinique'), ('mr', 'Mauritania'), ('mu', 'Mauritius'), ('yt', 'Mayotte'), ('mx', 'Mexico'), ('md', 'Moldova'), ('mc', 'Monaco'), ('mn', 'Mongolia'), ('me', 'Montenegro'), ('ms', 'Montserrat'), ('ma', 'Morocco'), ('mz', 'Mozambique'), ('mm', 'Myanmar'), ('na', 'Namibia'), ('nr', 'Nauru'), ('np', 'Nepal'), ('nl', 'Netherlands'), ('an', 'Netherlands Antilles'), ('nc', 'New Caledonia'), ('nz', 'New Zealand'), ('ni', 'Nicaragua'), ('ne', 'Niger'), ('ng', 'Nigeria'), ('nu', 'Niue'), ('nF', 'Norfolk Island'), ('mp', 'Northern Mariana Islands'), ('no', 'Norway'), ('om', 'Oman'), ('pk', 'Pakistan'), ('pw', 'Palau'), ('ps', 'Palestinian territories\tie, West Bank and Gaza Strip'), ('pa', 'Panama'), ('pg', 'Papua New Guinea'), ('py', 'Paraguay'), ('cn', "People's Republic of China"), ('pe', 'Peru'), ('ph', 'Philippines'), ('pn', 'Pitcairn Islands'), ('pl', 'Poland'), ('pt', 'Portugal'), ('pr', 'Puerto Rico'), ('qa', 'Qatar'), ('mk', 'Republic of Macedonia'), ('cg', 'Republic of the Congo'), ('ro', 'Romania'), ('ru', 'Russia'), ('rw', 'Rwanda'), ('re', 'Réunion'), ('sh', 'Saint Helena'), ('kn', 'Saint Kitts and Nevis'), ('lc', 'Saint Lucia'), ('vc', 'Saint Vincent and the Grenadines'), ('pm', 'Saint-Pierre and Miquelon'), ('ws', 'Samoa (Formerly Western Samoa)'), ('sm', 'San Marino'), ('sa', 'Saudi Arabia'), ('sn', 'Senegal'), ('rs', 'Serbia'), ('sc', 'Seychelles'), ('sl', 'Sierra Leone'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('sb', 'Solomon Islands'), ('so', 'Somalia'), ('za', 'South Africa'), ('gs', 'South Georgia and the South Sandwich Islands'), ('kr', 'South Korea'), ('su', 'Soviet Union'), ('es', 'Spain (España)'), ('lk', 'Sri Lanka'), ('sd', 'Sudan'), ('sr', 'Suriname'), ('sj', 'Svalbard and Jan Mayen Islands'), ('sz', 'Swaziland'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('sy', 'Syria'), ('st', 'São Tomé and Príncipe'), ('tw', 'Taiwan'), ('tj', 'Tajikistan'), ('tz', 'Tanzania'), ('th', 'Thailand'), ('gm', 'The Gambia'), ('tl', 'Timor-Leste'), ('tg', 'Togo'), ('tk', 'Tokelau'), ('to', 'Tonga'), ('tt', 'Trinidad and Tobago'), ('tn', 'Tunisia'), ('tr', 'Turkey'), ('tm', 'Turkmenistan'), ('tc', 'Turks and Caicos Islands'), ('tv', 'Tuvalu'), ('vi', 'US Virgin Islands'), ('ug', 'Uganda'), ('ua', 'Ukraine'), ('ae', 'United Arab Emirates'), ('gb', 'United Kingdom'), ('uk', 'United Kingdom'), ('um', 'United States Minor Outlying Islands'), ('us', 'United States of America'), ('uy', 'Uruguay'), ('uz', 'Uzbekistan'), ('vu', 'Vanuatu'), ('va', 'Vatican City State'), ('ve', 'Venezuela'), ('vn', 'Vietnam'), ('wf', 'Wallis and Futuna'), ('ye', 'Yemen'), ('yu', 'Yugoslavia'), ('zm', 'Zambia'), ('zw', 'Zimbabwe')], db_index=True, default='bd', max_length=2),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='diagnosis_with',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='patient diagnosis with'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='dropout_status',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Dead'), (3, 'Move to another organization')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='economic_status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Extreme Poor'), (1, 'Poor'), (2, 'Middle Class'), (3, 'Rich'), (4, 'Lower Middle Class'), (5, 'Upper Middle class'), (6, 'Emergency')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganization_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='family_relation',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, '-'), (1, 'Spouse'), (2, 'Son'), (3, 'Daughter'), (4, 'Son in law'), (5, 'Daughter in law'), (6, 'Father in law'), (7, 'Mother in law'), (8, 'Niece'), (9, 'Nephew'), (10, 'Uncle'), (11, 'Aunt'), (12, 'Head'), (13, 'Other')], db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='gender',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Transsexual'), (3, 'Any')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='hero_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='profiles/hero'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='language',
            field=models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Internal'), (2, 'External')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='profile_image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='profiles/pic'),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='relatives_relation',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Father'), (1, 'Mother'), (2, 'Spouse'), (3, 'Brother'), (4, 'Sister'), (5, 'Uncle'), (6, 'Aunt'), (7, 'Brother in Law'), (8, 'Sister in Law'), (9, 'Father in Law'), (10, 'Friends'), (11, 'Helping Hand'), (99, 'Other')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganization_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='personorganizationdiscount',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationdiscount_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='personorganizationdiscount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='personorganizationdiscount',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='personorganizationdiscount',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganizationdiscount',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationdiscount_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='personorganizationgrouppermission',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationgrouppermission_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='personorganizationgrouppermission',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='personorganizationgrouppermission',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganizationgrouppermission',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationgrouppermission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='personorganizationsalary',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationsalary_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='personorganizationsalary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='personorganizationsalary',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='personorganizationsalary',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganizationsalary',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_personorganizationsalary_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriberdesignation',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberdesignation_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriberdesignation',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriberdesignation',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriberdesignation',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberdesignation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='prescriberreferrercategory',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberreferrercategory_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='prescriberreferrercategory',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='prescriberreferrercategory',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriberreferrercategory',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_prescriberreferrercategory_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_referrercategory_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='referrercategory',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_referrercategory_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='disburse_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Tri Monthly'), (4, 'Yearly')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salarygrade_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salarygrade_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='amount_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Flat'), (2, 'Percentage')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salarygradeheads_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salarygradeheads',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salarygradeheads_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salaryhead_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='head_disburse_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Saving'), (2, 'Regular Payment'), (3, 'Regular Expense')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='is_global',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Private'), (1, 'Global'), (2, 'Changed into Global')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Addition'), (2, 'Deduction')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='salaryhead',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_salaryhead_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='scriptfilestorage',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_scriptfilestorage_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='scriptfilestorage',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='scriptfilestorage',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='scriptfilestorage',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_scriptfilestorage_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='entry_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_smslog_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='organization_wise_serial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_smslog_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
