# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20190918_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='referrer_organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
