# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_personorganization_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='purchase_fixed_rate',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable Purchase fix rate'),
        ),
    ]
