# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0045_auto_20191204_0633'),
        ('core', '0166_auto_20191202_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discarded_physical_tests',
            field=models.ManyToManyField(related_name='organization_of_discarded_physical_test', through='prescription.OrganizationWiseDiscardedPhysicalTest', to='prescription.PhysicalTest'),
        ),
    ]
