# Generated by Django 2.2.7 on 2019-12-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_organization_discarded_physical_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization'),
        ),
    ]
