# Generated by Django 2.2.8 on 2019-12-05 12:33

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20191205_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='global_subservice_category',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Category A'), (3, 'Category B')], db_index=True, default=1),
        ),
    ]
