# Generated by Django 2.2.8 on 2019-12-13 07:14

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_organizationsetting_global_subservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='group_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor')], db_index=True, default=0, null=True),
        ),
    ]
