# Generated by Django 2.2.9 on 2020-01-13 06:22

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20191213_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Mother'), (1, 'Branch'), (2, 'Unite'), (3, 'Private Practitioners'), (4, 'Pharmacy'), (5, 'Diagnostic'), (6, 'Distributor')], db_index=True, default=0),
        ),
    ]
