# Generated by Django 2.2.9 on 2020-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20200113_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='patient_tag',
            field=models.BooleanField(default=False, help_text='Settings for enable/disable tag in patient form'),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
