# Generated by Django 2.2.9 on 2020-02-07 06:37

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20200115_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='extra_settings',
            field=common.fields.JSONTextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='custom_field_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='custom_field_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='custom_field_3',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='personorganization',
            name='custom_field_4',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
