# Generated by Django 2.2.10 on 2020-04-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20200310_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='default_service_consumed_overall_discount_status',
            field=models.BooleanField(default=False, help_text='Default value of Service Consumed overall discout'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='default_service_consumed_patient_paying_status',
            field=models.BooleanField(default=False, help_text='Default value of Service Consumed patient advanced payment status'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='default_service_consumed_referrer_honorarium_status',
            field=models.BooleanField(default=False, help_text='Default value of Service Consumed referrer honorarium'),
        ),
    ]
