# Generated by Django 2.2.10 on 2020-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0153_organizationwisediscardedsubservice'),
        ('core', '0176_auto_20200427_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discarded_subservices',
            field=models.ManyToManyField(related_name='organization_of_discarded_subservice', through='clinic.OrganizationWiseDiscardedSubService', to='clinic.SubService'),
        ),
    ]
