# Generated by Django 2.2.10 on 2020-04-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0049_organizationwisediscardedlabtest'),
        ('core', '0177_organization_discarded_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discarded_lab_tests',
            field=models.ManyToManyField(related_name='organization_of_discarded_physical_test', through='prescription.OrganizationWiseDiscardedLabTest', to='prescription.LabTest'),
        ),
    ]
