# Generated by Django 2.2.13 on 2020-06-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20200609_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(max_length=2048),
        ),
    ]
