# Generated by Django 2.2.13 on 2020-06-30 14:32

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20200624_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pagination_type',
            field=enumerify.fields.SelectIntegerField(choices=[(1, 'Default'), (2, 'Scroll')], db_index=True, default=2),
        ),
    ]
