# Generated by Django 2.2.13 on 2020-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_organizationsetting_allow_procurement_product_add_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='allow_back_dated_transaction',
            field=models.BooleanField(default=False, help_text='This filed will define a user have permission for creating back dated transaction or not'),
        ),
    ]
