# Generated by Django 2.2.13 on 2020-07-27 13:15

from django.db import migrations
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_personorganization_allow_back_dated_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='delivery_thana',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, '-'), (302602, 'adabor'), (302604, 'badda'), (302605, 'bangshal'), (302606, 'biman_bandar'), (302607, 'banani'), (302608, 'cantonment'), (302609, 'chak_bazar'), (302610, 'dakshinkhan'), (302611, 'darus_salam'), (302612, 'demra'), (302614, 'dhamrai'), (302616, 'dhanmondi'), (302618, 'dohar'), (302621, 'bhasan_tek'), (302622, 'bhatara'), (302624, 'gendaria'), (302626, 'gulshan'), (302628, 'hazaribagh'), (302629, 'jatrabari'), (302630, 'kafrul'), (302632, 'kadamtali'), (302633, 'kalabagan'), (302634, 'kamrangir_char'), (302636, 'khilgaon'), (302637, 'khilkhet'), (302638, 'keraniganj'), (302640, 'kotwali'), (302642, 'lalbagh'), (302648, 'mirpur'), (302650, 'mohammadpur'), (302654, 'motijheel'), (302657, 'mugda_para'), (302662, 'nawabganj'), (302663, 'new_market'), (302664, 'pallabi'), (302665, 'paltan'), (302666, 'ramna'), (302667, 'rampura'), (302668, 'sabujbagh'), (302670, 'rupnagar'), (302672, 'savar'), (302673, 'shahjahanpur'), (302674, 'shah_ali'), (302675, 'shahbagh'), (302676, 'shyampur'), (302680, 'sher_e_bangla_nagar'), (302688, 'sutrapur'), (302690, 'tejgaon'), (302692, 'tejgaon_ind_area'), (302693, 'turag'), (302694, 'uttara_paschim'), (302695, 'uttara_purba'), (302696, 'uttar_khan'), (302698, 'wari')], db_index=True, default=None, null=True),
        ),
    ]
