# Generated by Django 2.2.13 on 2020-08-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_organization_delivery_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='buyer_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_buyer', to='core.Organization'),
        ),
    ]
