# Generated by Django 2.2.13 on 2020-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_personorganization_buyer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='dropout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
