# Generated by Django 2.2.13 on 2021-02-22 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0141_purchase_geo_location_data'),
        ('core', '0191_auto_20210209_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField(help_text='Date time for issue')),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Delivery'), (2, 'Return'), (3, 'Product'), (4, 'Pricing'), (5, 'Order Cancel'), (6, 'Others')], db_index=True, default=6, help_text='Define type of issue')),
                ('current_issue_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Processing'), (4, 'Resolved'), (5, 'Rejected')], db_index=True, default=1, help_text='Define current status of issue')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_issue_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='active_issue_count',
            field=models.IntegerField(default=0, help_text='Active issue count of an organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rating',
            field=models.IntegerField(default=5, help_text='Ratings of an organization', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date time for status changed')),
                ('issue_status', enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Pending'), (2, 'Accepted'), (3, 'Processing'), (4, 'Resolved'), (5, 'Rejected')], db_index=True, default=1, help_text='Define current status of issue')),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_issuestatus_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('issue', models.ForeignKey(help_text='The issue for status tracking', on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_status', to='core.Issue')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_issuestatus_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Issue Status',
                'verbose_name_plural': 'Issue Statuses',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_organization',
            field=models.ForeignKey(blank=True, help_text='Issue organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.ForeignKey(help_text='The order for related to issue', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_issues', to='pharmacy.Purchase'),
        ),
        migrations.AddField(
            model_name='issue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization', verbose_name='organization name'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization_reported_against', to='core.PersonOrganization'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization_reported_to', to='core.PersonOrganization'),
        ),
        migrations.AddField(
            model_name='issue',
            name='responsible_to_resolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_organization_responsible_to_resolve', to='core.PersonOrganization'),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_issue_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
