# Generated by Django 2.2.20 on 2021-05-06 11:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_auto_20210303_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptfilestorage',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Prediction params', null=True),
        ),
        migrations.AddField(
            model_name='scriptfilestorage',
            name='file_purpose',
            field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (1, 'Script'), (2, 'Distributor Stock'), (3, 'Purchase Prediction'), (4, 'Others')], db_index=True, default=1, help_text='Purpose to use of the file'),
        ),
        migrations.AddField(
            model_name='scriptfilestorage',
            name='prediction_on',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ScriptFileStorage'),
        ),
    ]
