# Generated by Django 2.2.20 on 2021-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20210506_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='delivery_sub_area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
