# Generated by Django 2.2.20 on 2021-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_authlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='phone',
            field=models.CharField(max_length=55),
        ),
    ]
