# Generated by Django 2.2.20 on 2021-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_organizationsetting_allow_order_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptfilestorage',
            name='set_stock_from_file',
            field=models.BooleanField(default=False),
        ),
    ]
