# Generated by Django 2.2.24 on 2021-11-03 07:30

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_organizationsetting_overwrite_order_mode_by_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='offer_rules',
            field=common.fields.JSONTextField(blank=True, default='[]', null=True),
        ),
    ]
