# Generated by Django 2.2.24 on 2021-12-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_organization_offer_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptfilestorage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
