# Generated by Django 2.2.25 on 2022-04-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_scriptfilestorage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referred_organizations', to='core.PersonOrganization', verbose_name='Person Organization who referred this organization'),
        ),
    ]
