# Generated by Django 2.2.25 on 2022-09-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_auto_20220901_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='discarded_heads',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='discarded_lab_tests',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='discarded_physical_tests',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='discarded_products',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='discarded_subservices',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_font_size',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_header',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_patient_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_patient_group',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='print_slogan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_label_appointment_print',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_label_consumed_print',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_label_sales_print',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_label_transaction_print',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slogan_font_size',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='transaction_receipt_note',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
    ]
