# Generated by Django 2.2.25 on 2022-10-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20220914_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsetting',
            old_name='bed_checkout_time',
            new_name='order_ending_time',
        ),
    ]
