# Generated by Django 4.1.5 on 2023-04-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_alter_authlog_entry_by_alter_authlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='order_re_opening_date',
            field=models.DateTimeField(blank=True, help_text='Order re-opening date', null=True),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='order_stopping_date',
            field=models.DateTimeField(blank=True, help_text='Order stopping date', null=True),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='order_stopping_message',
            field=models.TextField(blank=True, help_text='Order stopping message', null=True),
        ),
    ]
