# Generated by Django 4.1.6 on 2023-04-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_organizationsetting_order_re_opening_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='tagged_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.personorganization'),
        ),
    ]
