# Generated by Django 4.2.3 on 2023-08-30 10:01

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_organization_geo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('short_code', models.CharField(max_length=12, unique=True)),
                ('areas', django.contrib.postgres.fields.ArrayField(base_field=enumerify.fields.SelectIntegerField(choices=[(0, '-'), (302602, 'Adabor'), (302604, 'Badda'), (302605, 'Bangshal'), (302606, 'Biman Bandar'), (302607, 'Banani'), (302608, 'Cantonment'), (302609, 'Chak Bazar'), (302610, 'Dakshinkhan'), (302611, 'Darus Salam'), (302612, 'Demra'), (302614, 'Dhamrai'), (302616, 'Dhanmondi'), (302618, 'Dohar'), (302621, 'Bhasantek'), (302622, 'Bhatara'), (302624, 'Gendaria'), (302626, 'Gulshan'), (302628, 'Hazaribagh'), (302629, 'Jatrabari'), (302630, 'Kafrul'), (302632, 'Kadamtali'), (302633, 'Kalabagan'), (302634, 'Kamrangir Char'), (302636, 'Khilgaon'), (302637, 'Khilkhet'), (302638, 'Keraniganj'), (302640, 'Kotwali'), (302642, 'Lalbagh'), (302648, 'Mirpur'), (302650, 'Mohammadpur'), (302654, 'Motijheel'), (302657, 'Mugda Para'), (302662, 'Nawabganj'), (302663, 'Newmarket'), (302664, 'Pallabi'), (302665, 'Paltan'), (302666, 'Ramna'), (302667, 'Rampura'), (302668, 'Sabujbagh'), (302670, 'Rupnagar'), (302672, 'Savar'), (302673, 'Shahjahanpur'), (302674, 'Shah_ali'), (302675, 'Shahbagh'), (302676, 'Shyampur'), (302680, 'Sher-e-bangla Nagar'), (302688, 'Sutrapur'), (302690, 'Tejgaon'), (302692, 'Tejgaon Industrial Area'), (302693, 'Turag'), (302694, 'Uttara Paschim'), (302695, 'Uttara Purba'), (302696, 'Uttar Khan'), (302698, 'Wari'), (888888, 'Hatirjheel'), (999999, 'Others')], db_index=True, default=0), blank=True, default=list, null=True, size=None)),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Delivery Hub',
                'verbose_name_plural': 'Delivery Hubs',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='delivery_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_hub_organizations', to='core.deliveryhub'),
        ),
    ]
