# Generated by Django 4.2.4 on 2023-09-12 07:40

from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_deliveryhub_organization_delivery_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorganization',
            name='tagged_contractor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tagged_contractors_list', to='core.personorganization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor'), (12, 'Trader'), (13, 'Contractor')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='group_type',
            field=enumerify.fields.SelectIntegerField(choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor'), (12, 'Trader'), (13, 'Contractor')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='personorganization',
            name='person_group',
            field=enumerify.fields.SelectIntegerField(blank=True, choices=[(0, 'Patient'), (1, 'Employee'), (2, 'Stack Holder'), (3, 'Supplier'), (4, 'Board of Director'), (5, 'System Admin'), (6, 'Referrer'), (7, 'Service Provider'), (8, 'Other'), (9, 'Prescriber'), (10, 'Extra'), (11, 'Monitor'), (12, 'Trader'), (13, 'Contractor')], db_index=True, default=0, null=True),
        ),
    ]
