# Generated by Django 4.2.4 on 2023-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_person_delivery_hub_person_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhub',
            name='hub_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
