# Generated by Django 4.2.4 on 2023-11-15 06:15

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0222_remove_deliveryhub_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discount_factor",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_dynamic_discount_factor",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    enumerify.fields.SelectIntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "Inactive"),
                            (2, "Draft"),
                            (3, "Released"),
                            (4, "Approved Draft"),
                            (5, "Absent"),
                            (6, "Purchase Order"),
                            (7, "Suspend"),
                            (8, "On Hold"),
                            (9, "Hardwired"),
                            (10, "Loss"),
                            (11, "Freeze"),
                            (12, "For Adjustment"),
                            (13, "Distributor Order"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_wise_serial",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="OrganizationWise Serial Number",
                    ),
                ),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        allow_unicode=True,
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(max_length=24, unique=True)),
                (
                    "discount_factor",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
                ),
                (
                    "entry_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_entry_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="entry by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last updated by",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Area of an organization",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="area_organizations",
                to="core.area",
            ),
        ),
    ]
