# Generated by Django 4.2.4 on 2023-11-20 06:59

import autoslug.fields
import common.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumerify.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_organization_discount_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Released'), (4, 'Approved Draft'), (5, 'Absent'), (6, 'Purchase Order'), (7, 'Suspend'), (8, 'On Hold'), (9, 'Hardwired'), (10, 'Loss'), (11, 'Freeze'), (12, 'For Adjustment'), (13, 'Distributor Order')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='name')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('primary_mobile', models.CharField(max_length=20)),
                ('other_contact', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_person', models.CharField(max_length=64)),
                ('contact_person_designation', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('copies_while_print', models.TextField(blank=True, null=True)),
                ('show_global_product', models.BooleanField(default=False, help_text='Settings for show global products')),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, 'Mother'), (1, 'Branch'), (2, 'Unite'), (3, 'Private Practitioners'), (4, 'Pharmacy'), (5, 'Diagnostic'), (6, 'Distributor'), (7, 'Distributor Buyer')], db_index=True, default=0)),
                ('license_no', models.CharField(blank=True, max_length=128, null=True)),
                ('license_image', models.TextField(blank=True, max_length=100, null=True)),
                ('delivery_thana', enumerify.fields.SelectIntegerField(blank=True, choices=[(0, '-'), (302602, 'Adabor'), (302604, 'Badda'), (302605, 'Bangshal'), (302606, 'Biman Bandar'), (302607, 'Banani'), (302608, 'Cantonment'), (302609, 'Chak Bazar'), (302610, 'Dakshinkhan'), (302611, 'Darus Salam'), (302612, 'Demra'), (302614, 'Dhamrai'), (302616, 'Dhanmondi'), (302618, 'Dohar'), (302621, 'Bhasantek'), (302622, 'Bhatara'), (302624, 'Gendaria'), (302626, 'Gulshan'), (302628, 'Hazaribagh'), (302629, 'Jatrabari'), (302630, 'Kafrul'), (302632, 'Kadamtali'), (302633, 'Kalabagan'), (302634, 'Kamrangir Char'), (302636, 'Khilgaon'), (302637, 'Khilkhet'), (302638, 'Keraniganj'), (302640, 'Kotwali'), (302642, 'Lalbagh'), (302648, 'Mirpur'), (302650, 'Mohammadpur'), (302654, 'Motijheel'), (302657, 'Mugda Para'), (302662, 'Nawabganj'), (302663, 'Newmarket'), (302664, 'Pallabi'), (302665, 'Paltan'), (302666, 'Ramna'), (302667, 'Rampura'), (302668, 'Sabujbagh'), (302670, 'Rupnagar'), (302672, 'Savar'), (302673, 'Shahjahanpur'), (302674, 'Shah_ali'), (302675, 'Shahbagh'), (302676, 'Shyampur'), (302680, 'Sher-e-bangla Nagar'), (302688, 'Sutrapur'), (302690, 'Tejgaon'), (302692, 'Tejgaon Industrial Area'), (302693, 'Turag'), (302694, 'Uttara Paschim'), (302695, 'Uttara Purba'), (302696, 'Uttar Khan'), (302698, 'Wari'), (888888, 'Hatirjheel'), (999999, 'Others')], db_index=True, default=None, null=True)),
                ('delivery_sub_area', models.CharField(blank=True, max_length=128, null=True)),
                ('min_order_amount', models.FloatField(default=0.0)),
                ('rating', models.IntegerField(default=5, help_text='Ratings of an organization', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('active_issue_count', models.IntegerField(default=0, help_text='Active issue count of an organization')),
                ('offer_rules', common.fields.JSONTextField(blank=True, default='[]', null=True)),
                ('geo_location', models.JSONField(blank=True, default=dict, null=True)),
                ('has_dynamic_discount_factor', models.BooleanField(default=False)),
                ('discount_factor', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, help_text='Area of an organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.area')),
                ('delivery_hub', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.deliveryhub')),
                ('entry_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_responsible_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization', verbose_name='Person Organization who are primary responsible person of this organization')),
                ('referrer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization', verbose_name='Person Organization who referred this organization')),
                ('secondary_responsible_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.personorganization', verbose_name='Person Organization who are secondary responsible person of this organization')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'historical organization',
                'verbose_name_plural': 'historical organizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
