# Generated by Django 4.2.7 on 2023-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_alter_historicalorganization_delivery_thana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
