# Generated by Django 4.2.7 on 2023-12-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0174_purchase_is_delayed'),
        ('core', '0227_passwordreset_reset_date'),
        ('ecommerce', '0016_deliverysheetitem_invoice_group_delivery_sub_sheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_wise_serial', models.PositiveIntegerField(default=0, editable=False, help_text='OrganizationWise Serial Number')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('snapshot_date', models.DateField()),
                ('status', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('discount_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('sales_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('additional_discount_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('effective_sales_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('effective_sales_value', models.DecimalField(decimal_places=3, max_digits=19)),
                ('order_additional_discount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('order_grand_total', models.DecimalField(decimal_places=3, max_digits=19)),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('delivery_thana', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('employee_first_name', models.CharField(max_length=255)),
                ('employee_last_name', models.CharField(max_length=255)),
                ('total_short', models.IntegerField(default=0)),
                ('total_return', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personorganization')),
                ('entry_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('invoice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.orderinvoicegroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.purchase')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stock')),
                ('stock_io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stockiolog')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Daily Sale Snapshot',
                'unique_together': {('snapshot_date', 'stock_io', 'organization', 'product', 'invoice_group')},
                'index_together': {('snapshot_date', 'stock_io', 'organization', 'product', 'invoice_group')},
            },
        ),
    ]
